import type { NextPage } from "next";
import Head from "next/head";
import Grid from "../../components/Grid";
import Page from "../../components/Page";
import Section from "../../components/Section";
import { createLineAttribute } from "../../utils/lines";
import FeatureList from "../../components/FeatureList";
import ComponentPreview from "../../components/ComponentPreview";
import { components, componentCategories } from "../../data/components";
import styles from "../styles/Index.module.scss";
import Link from "next/link";
import { useRouter } from "next/router";
import SectionHead from "../../components/SectionHead";
import Masonry from "react-masonry-css";

interface Props {
  items: { url: string; label: string }[];
}

const Components: NextPage = () => {
  const router = useRouter();
  let { category } = router.query;

  return (
    <Page>
      <Head>
        <title>Components</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Section>
        <SectionHead
          title="Components"
          navItems={Object.entries(componentCategories).map(([name, meta]) => ({
            label: meta.label,
            url: `/components/${name}`,
          }))}
        />

        <Masonry
          breakpointCols={{
            default: 4,
            1800: 3,
            1400: 2,
            1000: 1,
          }}
          className="my-masonry-grid"
          columnClassName="my-masonry-grid_column"
        >
          {Object.entries(components)
            .filter(([name, meta]) => meta.category === category)
            .map(([name, meta]) => (
              <div
                key={name}
                style={{
                  border: `1px solid black`,
                  borderRadius: 2,
                }}
              >
                <ComponentPreview
                  id="iframe-card"
                  src={`/previews/components/${meta.previewId || "card"}`}
                  aspectRatio={0.5}
                />
                <Link href={`/components/${meta.category}/${name}`}>
                  <a
                    style={{
                      display: "block",
                      padding: "2em 2em 0.75em",
                      borderTop: "1px solid #ddd",
                    }}
                  >
                    <h3 style={{ color: "#333" }}>{name}</h3>
                    <p
                      {...createLineAttribute({
                        iframeSelector: "#iframe-page",
                        elementSelector: ".Polaris-ActionList__Actions",
                        fromOrigin: "edge",
                      })}
                    >
                      The {name} component makes it easy to lorem ipsum dolor et
                      amet consecteur. It has many props that allows for endless
                      customizability lorem ipsum dolor. Tell all your friends
                      about it.
                    </p>
                  </a>
                </Link>
              </div>
            ))}
        </Masonry>

        {/* <Grid center>
          <Grid.Column start={1} end={16}>
            <ComponentPreview
              id="iframe-page"
              src={`/previews/components/page`}
            />
          </Grid.Column>

          <Grid.Column start={17} end={25}>
            <h2>Page</h2>
            <p>
              The Page component makes it easy to lorem ipsum dolor et amet
              consecteur. It has many props that allows for endless
              customizability lorem ipsum dolor. Tell all your friends about it.
            </p>

            <FeatureList>
              <FeatureList.Item
                {...createLineAttribute({
                  iframeSelector: "#iframe-page",
                  elementSelector: ".Polaris-Header-Title",
                  fromOrigin: "edge",
                })}
              >
                Title
              </FeatureList.Item>

              <FeatureList.Item
                {...createLineAttribute({
                  iframeSelector: "#iframe-page",
                  elementSelector: ".Polaris-Header-Title__SubTitle",
                  fromOrigin: "edge",
                  toOrigin: "left",
                })}
              >
                Sub title
              </FeatureList.Item>

              <FeatureList.Item
                {...createLineAttribute({
                  iframeSelector: "#iframe-page",
                  elementSelector: ".Polaris-Badge",
                  fromOrigin: "edge",
                  toOrigin: "center",
                })}
              >
                Badge
              </FeatureList.Item>

              <FeatureList.Item
                {...createLineAttribute({
                  iframeSelector: "#iframe-page",
                  elementSelector: ".Polaris-ActionMenu-SecondaryAction",
                  fromOrigin: "edge",
                  toOrigin: "edge",
                })}
              >
                Page actions
              </FeatureList.Item>
            </FeatureList>
          </Grid.Column>
        </Grid> */}
      </Section>
    </Page>
  );
};

export default Components;
