import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Page from "../../components/Page";
import ComponentsNav from "../../components/ComponentsNav";
import components from "../../data/components.json";
import fs from "fs";
import path from "path";

interface Props {
  name: string;
  readme: string;
}

const Components: NextPage<Props> = ({ name, readme }) => {
  return (
    <Page noLayout>
      <Head>
        <title>Component</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <ComponentsNav />
    </Page>
  );
};

export default Components;
