filename: UNRELEASED-V4.md
include:
  - /^config\//
  - /^documentation\//
  - /^scripts\//
  - /^src\//
  - /^.babelrc$/
  - /^.eslintrc$/
  - /^.nvmrc$/
  - /^.prettierrc$/
  - /^app.json$/
  - /^LICENSE.md$/
  - /^package.json$/
  - /^tsconfig.json$/
inProgressMessage: missing an entry in UNRELEASED-V4.md
skipLabel: skip changelog
detailsUrl: https://github.com/Shopify/polaris-react/blob/version-4.0.0/UNRELEASED-V4.md
