filename: UNRELEASED.md
include:
  - /^config\//
  - /^documentation\//
  - /^scripts\//
  - /^src\//
  - /^.babelrc$/
  - /^.eslintrc$/
  - /^.nvmrc$/
  - /^.prettierrc$/
  - /^app.json$/
  - /^LICENSE.md$/
  - /^package.json$/
  - /^tsconfig.json$/
inProgressMessage: missing an entry in UNRELEASED.md
skipLabel: 🤖Skip Changelog
detailsUrl: https://github.com/Shopify/polaris-react/blob/master/UNRELEASED.md
