name: polaris-react
up:
  - node:
      yarn: v1.13.0
      version: v10.15.0 # to be kept in sync with .nvmrc and ci.yml
  - git_hooks:
      pre-commit: pre-commit

open:
  app: http://localhost:6006/
  shipit: https://shipit.shopify.io/shopify/polaris-react/production
  coverage: build/coverage/index.html

commands:
  # People new to the project might be tempted to run some
  # common commands, so let’s have them in here.
  # For a list of Common Commands in Projects, check out:
  # https://development.shopify.io/tools/dev/getting_started/Common-Commands-in-Projects
  build: yarn run build
  server: yarn run dev
  style: yarn run lint
  test: yarn run test
  test:coverage: yarn run test:coverage
  type-check: yarn run type-check
