name: polaris-react
up:
  - node:
      yarn: true
      version: v10.13.0 # to be kept in sync with .nvmrc, scripts/open-styleguide-pr.js, and .circleci/config.yml
  - git_hooks:
      pre-commit: pre-commit

open:
  app: http://localhost:6006/
  shipit: https://shipit.shopify.io/shopify/polaris-react/production

commands:
  # People new to the project might be tempted to run some
  # common commands, so let’s have them in here.
  # For a list of Common Commands in Projects, check out:
  # https://github.com/Shopify/dev/wiki/Common-Commands-in-Projects
  build: yarn run build
  server: yarn run dev
  style: yarn run lint
  test: yarn run test
  type-check: yarn run ts
