name: polaris
up:
  - node:
      yarn: v1.22.18
      version: v20.11.1 # to be kept in sync with .nvmrc
  - custom:
      name: Build monorepo
      met?: yarn build --output-logs=none
      meet: 'true'

commands:
  server: yarn dev
