name: polaris
up:
  - node:
      package_manager: pnpm@8.15.5
      pnpm: 8.15.5
      version: v20.11.1 # to be kept in sync with .nvmrc
  - custom:
      name: Build monorepo
      met?: pnpm build --output-logs=none
      meet: 'true'

commands:
  server: pnpm dev
