import path from 'path';
import {copyFile, mkdir, writeFile} from 'fs/promises';

import ora from 'ora';

/**
 * Self-hosts Inter.
 *
 * The site used to pull Inter from `cdn.shopify.com`. The archived site must
 * make no automatic requests to Shopify, so we copy the variable font out of
 * the `inter-ui` dependency and serve it ourselves.
 *
 * The `url()`s in the generated stylesheet are relative to the stylesheet, so
 * this works unchanged under any base path.
 */
const FONT_FILES = ['Inter-roman.var.woff2', 'Inter-italic.var.woff2'];

const fontCss = `/* Generated by scripts/gen-fonts.ts. Do not edit. */
@font-face {
  font-family: 'Inter var';
  font-weight: 100 900;
  font-style: normal;
  font-named-instance: 'Regular';
  font-display: swap;
  src: url('Inter-roman.var.woff2') format('woff2 supports variations(gvar)'),
    url('Inter-roman.var.woff2') format('woff2-variations'),
    url('Inter-roman.var.woff2') format('woff2');
}

@font-face {
  font-family: 'Inter var';
  font-weight: 100 900;
  font-style: italic;
  font-named-instance: 'Italic';
  font-display: swap;
  src: url('Inter-italic.var.woff2') format('woff2 supports variations(gvar)'),
    url('Inter-italic.var.woff2') format('woff2-variations'),
    url('Inter-italic.var.woff2') format('woff2');
}

/*
 * The site's stylesheets ask for \`Inter\`; alias it to the variable font so we
 * only ship two files instead of the full static family.
 */
@font-face {
  font-family: 'Inter';
  font-weight: 100 900;
  font-style: normal;
  font-display: swap;
  src: url('Inter-roman.var.woff2') format('woff2-variations'),
    url('Inter-roman.var.woff2') format('woff2');
}

@font-face {
  font-family: 'Inter';
  font-weight: 100 900;
  font-style: italic;
  font-display: swap;
  src: url('Inter-italic.var.woff2') format('woff2-variations'),
    url('Inter-italic.var.woff2') format('woff2');
}
`;

const genFonts = async () => {
  const spinner = ora('Generating public/fonts/inter').start();

  const interDir = path.join(
    path.dirname(require.resolve('inter-ui/package.json')),
    'Inter (web)',
  );
  const outputDir = path.join(process.cwd(), 'public', 'fonts', 'inter');

  await mkdir(outputDir, {recursive: true});

  await Promise.all(
    FONT_FILES.map((fileName) =>
      copyFile(path.join(interDir, fileName), path.join(outputDir, fileName)),
    ),
  );

  await writeFile(path.join(outputDir, 'inter.css'), fontCss, 'utf-8');

  spinner.succeed('Generated public/fonts/inter');
};

export default genFonts;
