export interface Order {
  id: string;
  date: string;
  customer: string;
  channel: string;
  total: string;
  paymentStatus: string[];
  fulfillmentStatus: string[];
  status: string;
  items: string;
  deliveryMethod: string;
  tags: string;
}

export const orders: Order[] = [
  {
    id: '1053',
    date: 'Aug 22, 2024 at 11:11 pm',
    customer: 'Ian Nikolaus',
    channel: 'Online Store',
    total: '$2,051.20',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Unfulfilled'],
    items: '8,205',
    deliveryMethod: 'Ground',
    status: 'Open',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1052',
    date: 'Aug 22, 2024 at 5:13 am',
    customer: 'Esmeralda Ernser',
    channel: 'TikTok',
    total: '$35.58',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Unfulfilled'],
    items: '22',
    deliveryMethod: 'Express',
    status: 'Open',
    tags: 'gift wrap',
  },
  {
    id: '1051',
    date: 'Aug 21, 2024 at 9:59 am',
    customer: 'Lindsay Gorczany',
    channel: 'TikTok',
    total: '$79.86',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '319',
    deliveryMethod: '2 Day Air',
    status: 'Open',
    tags: '',
  },
  {
    id: '1050',
    date: 'Aug 20, 2024 at 11:47 am',
    customer: 'Brennan Schowalter',
    channel: 'TikTok',
    total: '$207.24',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Partially fulfilled'],
    items: '829',
    deliveryMethod: 'Standard',
    status: 'Open',
    tags: '',
  },
  {
    id: '1049',
    date: 'Aug 20, 2024 at 2:56 am',
    customer: 'Ryder Glover',
    channel: 'TikTok',
    total: '$438.15',
    paymentStatus: ['Payment pending'],
    fulfillmentStatus: ['Partially fulfilled'],
    items: '1,753',
    deliveryMethod: 'Standard',
    status: 'Open',
    tags: '',
  },
  {
    id: '1048',
    date: 'Aug 20, 2024 at 2:14 am',
    customer: 'Dillon Weissnat',
    channel: 'TikTok',
    total: '$577.10',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Partially fulfilled'],
    items: '2,308',
    deliveryMethod: 'Standard',
    status: 'Open',
    tags: '',
  },
  {
    id: '1047',
    date: 'Jul 18, 2024 at 6:46 am',
    customer: 'Patrick Gerlach',
    channel: 'Online Store',
    total: '$56.73',
    paymentStatus: ['Payment pending', 'Overdue'],
    fulfillmentStatus: ['Unfulfilled'],
    items: '227',
    deliveryMethod: 'Standard',
    status: 'Open',
    tags: '',
  },
  {
    id: '1046',
    date: 'Jul 6, 2024 at 9:31 pm',
    customer: 'Melany Sauer',
    channel: 'Online Store',
    total: '$237.28',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '949',
    deliveryMethod: 'Express',
    status: 'Open',
    tags: '',
  },
  {
    id: '1045',
    date: 'Jul 4, 2024 at 8:26 am',
    customer: 'Walton Rowe',
    channel: 'Online Store',
    total: '$527.76',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '2,111',
    deliveryMethod: 'Standard',
    status: 'Open',
    tags: 'wholesale, net 30',
  },
  {
    id: '1044',
    date: 'Jun 26, 2024 at 11:04 am',
    customer: 'Walton Rowe',
    channel: 'Online Store',
    total: '$555.51',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '556',
    deliveryMethod: 'Standard',
    status: 'Open',
    tags: 'wholesale, net 30',
  },
  {
    id: '1043',
    date: 'Jun 21, 2024 at 10:43 pm',
    customer: 'Maxine Weimann',
    channel: 'Online Store',
    total: '$1,413.86',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '2,828',
    deliveryMethod: 'Ground',
    status: 'Open',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1042',
    date: 'Jun 17, 2024 at 6:32 pm',
    customer: 'Erin Torphy',
    channel: 'Online Store',
    total: '$1,266.79',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '5,067',
    deliveryMethod: 'Ground',
    status: 'Open',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1041',
    date: 'Jun 14, 2024 at 10:14 pm',
    customer: 'Reginald Herzog',
    channel: 'Online Store',
    total: '$1,786.00',
    paymentStatus: ['Refunded'],
    fulfillmentStatus: ['Fulfilled'],
    items: '7,144',
    deliveryMethod: 'Ground',
    status: 'Canceled',
    tags: 'vip, wholesale, net 60, damaged in shipment',
  },
  {
    id: '1040',
    date: 'Jun 3, 2024 at 6:17 am',
    customer: 'Talia Erdman',
    channel: 'TikTok',
    total: '$38.81',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '49',
    deliveryMethod: 'Standard',
    status: 'Open',
    tags: '',
  },
  {
    id: '1039',
    date: 'Apr 21, 2024 at 6:47 pm',
    customer: 'Walton Rowe',
    channel: 'Online Store',
    total: '$1,953.14',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '7,813',
    deliveryMethod: 'Standard',
    status: 'Open',
    tags: 'wholesale, net 30',
  },
  {
    id: '1038',
    date: 'Feb 17, 2024 at 7:03 am',
    customer: 'Walton Rowe',
    channel: 'Online Store',
    total: '$1,868.27',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '7,473',
    deliveryMethod: 'Standard',
    status: 'Open',
    tags: 'wholesale, net 30',
  },
  {
    id: '1037',
    date: 'Jan 27, 2024 at 5:31 pm',
    customer: 'Walton Rowe',
    channel: 'Online Store',
    total: '$663.45',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '2,654',
    deliveryMethod: 'Standard',
    status: 'Open',
    tags: 'wholesale, net 30',
  },
  {
    id: '1036',
    date: 'Jan 11, 2024 at 10:40 am',
    customer: 'Walton Rowe',
    channel: 'Online Store',
    total: '$2,080.11',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '8,320',
    deliveryMethod: 'Standard',
    status: 'Open',
    tags: 'wholesale, net 30',
  },
  {
    id: '1035',
    date: ' Dec 28, 2023',
    customer: 'Alia Simonis',
    channel: 'Instagram',
    total: '$165.54',
    paymentStatus: ['Refunded'],
    fulfillmentStatus: ['Unfulfilled'],
    items: '662',
    deliveryMethod: 'Overnight',
    status: 'Canceled',
    tags: 'gift, overnight deadline missed ',
  },
  {
    id: '1034',
    date: ' Dec 5, 2023',
    customer: 'Dario Krajcik',
    channel: 'Online Store',
    total: '$865.93',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '3,464',
    deliveryMethod: 'Express',
    status: 'Open',
    tags: '',
  },
  {
    id: '1033',
    date: ' Nov 29, 2023',
    customer: 'Maxine Weimann',
    channel: 'Online Store',
    total: '$3,091.17',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '12,365',
    deliveryMethod: 'Ground',
    status: 'Open',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1032',
    date: ' Sep 2, 2023',
    customer: 'Kenton Luettgen',
    channel: 'Online Store',
    total: '$957.20',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '3,829',
    deliveryMethod: 'Standard',
    status: 'Open',
    tags: '',
  },
  {
    id: '1031',
    date: ' Jul 17, 2023',
    customer: 'Reginald Herzog',
    channel: 'Online Store',
    total: '$3,063.09',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '12,252',
    deliveryMethod: 'Ground',
    status: 'Open',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1030',
    date: ' Jun 27, 2023',
    customer: 'Laverna Daniel',
    channel: 'Online Store',
    total: '$486.64',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '1,947',
    deliveryMethod: 'Standard',
    status: 'Open',
    tags: '',
  },
  {
    id: '1029',
    date: ' Jun 12, 2023',
    customer: 'Maxine Weimann',
    channel: 'Online Store',
    total: '$2,898.38',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '11,594',
    deliveryMethod: 'Ground',
    status: 'Open',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1028',
    date: ' May 19, 2023',
    customer: 'Guy Haley',
    channel: 'Instagram',
    total: '$361.90',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '1,448',
    deliveryMethod: 'Express',
    status: 'Open',
    tags: '',
  },
  {
    id: '1027',
    date: ' May 8, 2023',
    customer: 'Rico Bednar',
    channel: 'Instagram',
    total: '$3,839.03',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '15,356',
    deliveryMethod: 'Standard',
    status: 'Open',
    tags: '',
  },
  {
    id: '1026',
    date: ' May 6, 2023',
    customer: 'Aisha Bahringer',
    channel: 'Instagram',
    total: '$1,666.90',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '6,668',
    deliveryMethod: 'Standard',
    status: 'Open',
    tags: '',
  },
  {
    id: '1025',
    date: ' Apr 14, 2023',
    customer: 'Ian Nikolaus',
    channel: 'Online Store',
    total: '$4,081.40',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '16,326',
    deliveryMethod: 'Ground',
    status: 'Open',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1024',
    date: ' Mar 24, 2023',
    customer: 'Reginald Herzog',
    channel: 'Online Store',
    total: '$1,326.84',
    paymentStatus: ['Refunded'],
    fulfillmentStatus: ['Fulfilled'],
    items: '5,307',
    deliveryMethod: 'Ground',
    status: 'Canceled',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1023',
    date: ' Feb 25, 2023',
    customer: 'Walton Rowe',
    channel: 'Online Store',
    total: '$495.99',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '1,984',
    deliveryMethod: 'Express',
    status: 'Open',
    tags: 'wholesale, net 30',
  },
  {
    id: '1022',
    date: ' Feb 25, 2023',
    customer: 'Maxine Weimann',
    channel: 'Online Store',
    total: '$1,197.61',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '4,790',
    deliveryMethod: 'Ground',
    status: 'Open',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1021',
    date: ' Feb 10, 2023',
    customer: 'Rickey Thompson',
    channel: 'Online Store',
    total: '$1,575.27',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '6,301',
    deliveryMethod: 'Ground',
    status: 'Open',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1020',
    date: ' Jan 15, 2023',
    customer: 'Erin Torphy',
    channel: 'Online Store',
    total: '$2,194.11',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '8,776',
    deliveryMethod: 'Ground',
    status: 'Open',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1019',
    date: ' Jan 8, 2023',
    customer: 'Maxine Weimann',
    channel: 'Online Store',
    total: '$4,836.76',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '19,347',
    deliveryMethod: 'Ground',
    status: 'Open',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1018',
    date: ' Dec 10, 2022',
    customer: 'Ian Nikolaus',
    channel: 'Online Store',
    total: '$5,183.79',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '20,735',
    deliveryMethod: 'Ground',
    status: 'Archived',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1017',
    date: ' Nov 26, 2022',
    customer: 'Kailyn Paucek',
    channel: 'Online Store',
    total: '$653.15',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '2,613',
    deliveryMethod: 'Express',
    status: 'Archived',
    tags: '',
  },
  {
    id: '1016',
    date: ' Oct 13, 2022',
    customer: 'Walton Rowe',
    channel: 'Online Store',
    total: '$4,840.18',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '19,361',
    deliveryMethod: 'Standard',
    status: 'Archived',
    tags: 'wholesale, net 30',
  },
  {
    id: '1015',
    date: ' Sep 2, 2022',
    customer: 'Reginald Herzog',
    channel: 'Online Store',
    total: '$4,788.04',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '19,152',
    deliveryMethod: 'Ground',
    status: 'Archived',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1014',
    date: ' Aug 1, 2022',
    customer: 'Erin Torphy',
    channel: 'Online Store',
    total: '$5,784.50',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '23,138',
    deliveryMethod: 'Ground',
    status: 'Archived',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1013',
    date: ' Jul 9, 2022',
    customer: 'Ian Nikolaus',
    channel: 'Online Store',
    total: '$4,779.71',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '19,119',
    deliveryMethod: 'Ground',
    status: 'Archived',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1012',
    date: ' Jun 3, 2022',
    customer: 'Erin Torphy',
    channel: 'Online Store',
    total: '$4,488.62',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '17,954',
    deliveryMethod: 'Ground',
    status: 'Archived',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1011',
    date: ' Apr 4, 2022',
    customer: 'Ian Nikolaus',
    channel: 'Online Store',
    total: '$6,031.40',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '24,126',
    deliveryMethod: 'Ground',
    status: 'Archived',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1010',
    date: ' Jan 26, 2022',
    customer: 'Rickey Thompson',
    channel: 'Online Store',
    total: '$2,072.20',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '8,289',
    deliveryMethod: 'Ground',
    status: 'Archived',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1009',
    date: ' Dec 21, 2021',
    customer: 'Ian Nikolaus',
    channel: 'Online Store',
    total: '$5,132.97',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '20,532',
    deliveryMethod: 'Ground',
    status: 'Archived',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1008',
    date: ' Nov 7, 2021',
    customer: 'Erin Torphy',
    channel: 'Online Store',
    total: '$7,152.06',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '28,608',
    deliveryMethod: 'Ground',
    status: 'Archived',
    tags: 'vip, wholesale, net 60',
  },
  {
    id: '1007',
    date: ' Oct 10, 2021',
    customer: 'Sunny Harris',
    channel: '',
    total: '$22.83',
    paymentStatus: ['Refunded'],
    fulfillmentStatus: ['Unfulfilled'],
    items: '91',
    deliveryMethod: 'Local delivery',
    status: 'Canceled',
    tags: '',
  },
  {
    id: '1006',
    date: ' Sep 28, 2021',
    customer: 'Domenic Johnston',
    channel: '',
    total: '$33.88',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '136',
    deliveryMethod: 'Local delivery',
    status: 'Archived',
    tags: '',
  },
  {
    id: '1005',
    date: ' Sep 20, 2021',
    customer: 'Cassie Tromp',
    channel: '',
    total: '$27.22',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '109',
    deliveryMethod: 'Pickup',
    status: 'Archived',
    tags: '',
  },
  {
    id: '1004',
    date: ' Aug 24, 2021',
    customer: 'Anika Ankunding',
    channel: '',
    total: '$91.91',
    paymentStatus: ['Paid'],
    fulfillmentStatus: ['Fulfilled'],
    items: '138',
    deliveryMethod: 'Local delivery',
    status: 'Archived',
    tags: '',
  },
];
