#!/usr/bin/env node --harmony_destructuring

const fs = require('fs');
const path = require('path');
const shell = require('shelljs');

const componentName = process.argv[2];
const componentDir = path.join('src', 'components', componentName);

shell.mkdir('-p', componentDir);

fs.writeFileSync(path.join(componentDir, `${componentName}.scss`), `
.${componentName} {

}
`.trim());

fs.writeFileSync(path.join(componentDir, `${componentName}.js`), `
// @flow

import React from 'react';
import styles from './index.scss';

type Props = {
  children?: any,
};

export default function ${componentName}({children}: Props) {
  return (
    <div className={styles.${componentName}}>
      {children}
    </div>
  );
}
`.trim());

fs.writeFileSync(path.join(componentDir, 'index.js'), `
// @flow

import ${componentName} from './${componentName}';

export default ${componentName};
`.trim());
