#!/usr/bin/env node --harmony_destructuring

const fs = require('fs');
const path = require('path');
const shell = require('shelljs');

const componentName = process.argv[2];
const componentDir = path.join('src', 'components', componentName);

shell.mkdir('-p', componentDir);

fs.writeFileSync(path.join(componentDir, 'index.scss'), `
.${componentName} {

}
`.trim());

fs.writeFileSync(path.join(componentDir, 'index.js'), `
import React, {PropTypes} from 'react';
import styles from './index.scss';

export default function ${componentName}() {
  return (
    <div className={styles.${componentName}}>
    </div>
  );
}

${componentName}.propTypes = {
  children: PropTypes.node,
};

${componentName}.defaultProps = {

};
`.trim());
