import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Page from "../components/Page";
import icons from "../data/icons.json";

const Components: NextPage = () => {
  const [selectedIconName, setSelectedIconName] = useState<string>();

  const selectedIcon = icons.find((icon) => icon.name === selectedIconName);

  return (
    <Page
      noLayout
      sidebarRight={() => (
        <div
          style={{
            width: 480,
            padding: "2em",
          }}
        >
          {selectedIcon && (
            <>
              <h3>{selectedIcon.name}</h3>
              <p>{selectedIcon.description}</p>
              <ul>
                {selectedIcon.keywords.map((keyword) => (
                  <li key={keyword}>{keyword}</li>
                ))}
              </ul>
              <p>Contributed by: {selectedIcon.authors}</p>
            </>
          )}
        </div>
      )}
    >
      <Head>
        <title>Icons</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <ul
        style={{
          display: "flex",
          flexWrap: "wrap",
          padding: 100,
        }}
      >
        {icons.map((icon) => (
          <li
            key={`${icon.name}+${icon.set}`}
            style={{
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              width: "100%",
              minWidth: 200,
              flex: 1,
              padding: `45px 0 40px`,
              gap: 15,
              textAlign: "center",
              cursor: "pointer",
            }}
            onClick={() => setSelectedIconName(icon.name)}
          >
            <div style={{ filter: "brightness(-500%)" }}>
              <Image
                src={`/icons/${icon.fileName}.svg`}
                alt={icon.description}
                width={20}
                height={20}
              />
            </div>
            <span style={{ fontSize: 12, color: "#aaa" }}>{icon.name}</span>
          </li>
        ))}
      </ul>
    </Page>
  );
};

export default Components;
