import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Grid from "../components/Grid";
import Page from "../components/Page";
import Section from "../components/Section";
import icons from "../data/icons.json";

const Components: NextPage = () => {
  return (
    <Page>
      <Head>
        <title>Icons</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Section>
        <Grid center>
          <Grid.Column start={6} end={20}>
            <h1>Icons</h1>
            <p className="lede">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit in voluptate velit esse cillum dolore eu.
            </p>
          </Grid.Column>
        </Grid>

        <Grid center>
          <Grid.Column start={1} end={26}>
            <ul
              style={{
                display: "flex",
                flexWrap: "wrap",
                gap: 12,
              }}
            >
              {icons.map((icon) => (
                <li
                  key={`${icon.name}+${icon.set}`}
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    justifyContent: "center",
                    gap: ".5em",
                    width: 200,
                    padding: `40px 0 34px`,
                    textAlign: "center",
                    boxShadow: `0 0 0 1px black`,
                    borderRadius: 2,
                  }}
                >
                  <div style={{ filter: "brightness(-500%)" }}>
                    <Image
                      src={`/icons/${icon.fileName}.svg`}
                      alt={icon.description}
                      width={32}
                      height={32}
                    />
                  </div>
                  <span style={{ color: "#888", fontSize: 14 }}>
                    {icon.name}
                  </span>
                </li>
              ))}
            </ul>
          </Grid.Column>
        </Grid>
      </Section>
    </Page>
  );
};

export default Components;
