import type { NextPage } from "next";
import Head from "next/head";

import Page from "../components/Page";
import IconGallery from "../components/IconGallery";

const Components: NextPage = () => {
  return (
    <Page noLayout>
      <Head>
        <title>Icons</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <IconGallery />
    </Page>
  );
};

export default Components;
