import type { NextPage } from "next";
import Head from "next/head";
import Page from "../components/Page";

const Home: NextPage = () => {
  return (
    <Page>
      <Head>
        <title>Polaris</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1 style={{ textAlign: "left" }}>
        A Design System
        <br />
        Built for Commerce
      </h1>

      <a href="">
        <h3>
          <span className="subdued">Polaris for</span> React &rarr;
        </h3>
        <p>
          A new look and feel, with an updated color palette, icons, and more. A
          reduction to our bundle size and accessibility features to make sure
          that the experiences you create work.
        </p>
      </a>

      <a href="">
        <h3>
          <span className="subdued">Polaris for</span> VSCode &rarr;
        </h3>
        <p>
          A new look and feel, with an updated color palette, icons, and more. A
          reduction to our bundle size and accessibility features to make sure
          that the experiences you create work.
        </p>
      </a>

      <a href="">
        <h3>
          <span className="subdued">Polaris for</span> Figma &rarr;
        </h3>
        <p>
          A new look and feel, with an updated color palette, icons, and more. A
          reduction to our bundle size and accessibility features to make sure
          that the experiences you create work.
        </p>
      </a>
    </Page>
  );
};

export default Home;
