import type { NextPage } from "next";
import Head from "next/head";
import Page from "../components/Page";
import Section from "../components/Section";
import designSystemsAreFlawed from "../../public/design-systems-are-flawed.jpg";
import Image from "next/image";
import styles from "../styles/Index.module.scss";
import Grid from "../components/Grid";

const Home: NextPage = () => {
  return (
    <Page>
      <Head>
        <title>Polaris</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Section>
        <Grid>
          <Grid.Column start={3} end={22}>
            <h1 style={{ textAlign: "left" }}>
              A Design System
              <br />
              Built for Commerce
            </h1>
          </Grid.Column>

          <Grid.Column start={3} end={10}>
            <a href="">
              <h3>
                <span className="subdued">Polaris for</span> React &rarr;
              </h3>
              <p>
                A new look and feel, with an updated color palette, icons, and
                more. A reduction to our bundle size and accessibility features
                to make sure that the experiences you create work.
              </p>
            </a>
          </Grid.Column>

          <Grid.Column start={10} end={17}>
            <a href="">
              <h3>
                <span className="subdued">Polaris for</span> VSCode &rarr;
              </h3>
              <p>
                A new look and feel, with an updated color palette, icons, and
                more. A reduction to our bundle size and accessibility features
                to make sure that the experiences you create work.
              </p>
            </a>
          </Grid.Column>

          <Grid.Column start={17} end={24}>
            <a href="">
              <h3>
                <span className="subdued">Polaris for</span> Figma &rarr;
              </h3>
              <p>
                A new look and feel, with an updated color palette, icons, and
                more. A reduction to our bundle size and accessibility features
                to make sure that the experiences you create work.
              </p>
            </a>
          </Grid.Column>
        </Grid>
      </Section>
    </Page>
  );
};

export default Home;
