name: Propose new icon
description: Propose a new icon to polaris-icons
title: '[Icon]: '
labels: ['Icon']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out the proposal for a new icon!
  - type: textarea
    id: icon-usage
    attributes:
      label: How will these icons be used?
      value: |
        Relevant screenshots or links to Figma files detailing the entire user experience, the reason for creating the new icon(s), and any additional context.

        Have you already explored any possibilities for the new icons? Or do you have any ideas?
    validations:
      required: true
  - type: input
    id: icon-name
    attributes:
      label: Icon name
      value: arrow down
    validations:
      required: true
  - type: dropdown
    id: icon-set
    attributes:
      label: What type of icon set?
      options:
        - Major (20x20)
        - Minor (16x16)
        - Unsure
    validations:
      required: true
  - type: textarea
    id: icon-description
    attributes:
      label: Icon description
      value: |
        Action      | Used to denote <x action>.
        Wayfinding  | Used to help direct merchants to <x>.
        Concept     | Used to represent <x>.
        Education   | Used to give merchants more information about <context x>.
    validations:
      required: true
    render: bash
  - type: input
    id: icon-keywords
    attributes:
      label: Icon keywords
      value: orders, sales, funnel
    validations:
      required: true
  - type: input
    id: icon-author
    attributes:
      label: Icon author
  - type: textarea
    id: icon-svg
    attributes:
      label: Icon SVG code
      value: <svg>[your svg]/svg>
    render: bash
  - type: textarea
    id: icon-other-details
    attributes:
      label: Are there any other important details?
