name: New component proposal
description: Propose a new component
labels: ['Component', 'untriaged']
body:
  - type: input
    id: component-name
    attributes:
      label: Component name
      description: Provide the proposed component name.
  - type: textarea
    id: description
    attributes:
      label: Component description
      description: Provide a short, two sentence intro description.
      value: |
        {Component name} is used to {x}. Merchants can use it to {x}.
  - type: textarea
    id: required-components
    attributes:
      label: Required components
      description: |
        This section is only used if the component is a dependency of or depends on another component. 
        Include a link to the required component and a short explanation of how they interact.
      value: The {x} component must be {wrapped in/passed to} the {y} component.
  - type: textarea
    id: component-example
    attributes:
      label: Component example
      description: |
        Provide an example of the way the component would be used.
        Use an image if applicable and clearly differentiate examples from each other.
      value: |
        ### {Component name} with {example}
        Use {component name} to let merchants {x}.

        ![image-name](image-url)
  - type: textarea
    id: props
    attributes:
      label: Props
      description: Provide props and their type declarations.
      value: |
        - **propName** (required/optional): `type` defaults to `value` – description of the prop
        - **propName** (required/optional): `type` defaults to `value` – description of the prop
        - **propName** (required/optional): `type` defaults to `value` – description of the prop
  - type: textarea
    id: best-practices
    attributes:
      label: Best practices
      description: Provide best practices for the proposed component.
      value: |
        The {component name} component should:

        - {ux guideline}
        - {design best practice}
  - type: textarea
    id: content-guidelines
    attributes:
      label: Content guidelines
      description: Provide content guidelines for the proposed component.
      value: |
        The {component name} component should:

        - {guideline}

        | Do example | Don’t example |
        | ---------- | ------------- |
        | Do this    | Don’t do this |
  - type: textarea
    id: related-components
    attributes:
      label: Related components
      description: Provide components related to the proposed component.
      value: |
        - To {description for how related component works}, use the [{component name} component]
