import type Fuse from 'fuse.js';

import {
  GroupedSearchResults,
  SearchResultCategory,
  SearchResults,
  searchResultCategories,
} from '../types';

/**
 * Where the pre-built search index lands in `public/`. It's generated by
 * `scripts/gen-search-index.ts` and fetched lazily the first time somebody
 * opens the search dialog.
 *
 * This used to be the `/api/search/v0` route. The site is a static export now,
 * so there is no server to run Fuse on — the same corpus is built once at
 * export time and the matching happens in the browser instead.
 */
export const SEARCH_INDEX_PATH = '/search-index.json';

const MAX_RESULTS: {[key in SearchResultCategory]: number} = {
  foundations: 8,
  components: 6,
  patterns: 6,
  tokens: 5,
  icons: 9,
};

export const fuseOptions: Fuse.IFuseOptions<SearchResults[number]> = {
  keys: [
    // Foundations
    {name: 'meta.foundations.title', weight: 100},
    {name: 'meta.foundations.description', weight: 50},

    // Patterns
    {name: 'meta.patterns.title', weight: 100},
    {name: 'meta.patterns.description', weight: 50},

    // Components
    {name: 'meta.components.title', weight: 100},
    {name: 'meta.components.description', weight: 50},

    // Tokens
    {name: 'meta.tokens.token.name', weight: 200},
    {name: 'meta.tokens.token.value', weight: 50},

    // Icons
    {name: 'meta.icons.icon.fileName', weight: 50},
    {name: 'meta.icons.icon.name', weight: 50},
    {name: 'meta.icons.icon.keywords', weight: 20},
    {name: 'meta.icons.icon.description', weight: 50},
  ],
  includeScore: true,
  threshold: 0.5,
  shouldSort: true,
  ignoreLocation: true,
};

/**
 * Run a query against the pre-built index and bucket the hits by category.
 * Previously the body of the `/api/search/v0` handler.
 */
export function groupSearchResults(
  fuse: Fuse<SearchResults[number]>,
  query?: string,
): GroupedSearchResults {
  if (query == null || query.length === 0) return [];

  const scoredResults: SearchResults = fuse
    .search(query)
    .map((result) => ({...result.item, score: result.score || 0}));

  const groupedResults: GroupedSearchResults = searchResultCategories.map(
    (category) => ({
      category,
      results: scoredResults
        .filter((result) => result.category === category)
        .slice(0, MAX_RESULTS[category]),
    }),
  );

  groupedResults.sort(
    (a, b) => (a.results[0]?.score || 0) - (b.results[0]?.score || 0),
  );

  return groupedResults;
}
