/**
 * Stylelint config to ensure compliance with Polaris and improve coverage.
 */

/**
 * @type {import('stylelint').Config}
 */
module.exports = {
  plugins: ['stylelint-scss', '../plugins/global-disallowed-list'],
  rules: {
    'at-rule-disallowed-list': [['keyframes'], {severity: 'warning'}],
    'color-named': ['never', {severity: 'warning'}],
    'color-no-hex': [true, {severity: 'warning'}],
    'declaration-property-value-disallowed-list': [
      {
        display: ['grid', 'flex'],
        top: [/^(?!var\(--p-).+$/],
        bottom: [/^(?!var\(--p-).+$/],
        left: [/^(?!var\(--p-).+$/],
        right: [/^(?!var\(--p-).+$/],
        width: [/^(?!var\(--p-).+$/],
        height: [/^(?!var\(--p-).+$/],
        // Allow `0`, `1`, values between 0 and 1 (limit 2 decimal places), and custom properties
        // https://regex101.com/r/kIlVrQ/1
        opacity: [/^(?!0|1)\d$|^\d{2,}|^[1-9]+\.|^\d+\.\d+\.|^0\.\d{3,}/],
        'z-index': [/^(?!var\(--p-).+$/],
        'font-weight': [/(\$.*|[0-9]+)/],
      },
      {severity: 'warning'},
    ],
    'function-disallowed-list': [
      [
        'brightness',
        'contrast',
        'hue-rotate',
        'hsl',
        'hsla',
        'invert',
        'rgb',
        'rgba',
        'sepia',
        'available-names',
        'border-radius',
        'border-width',
        'border',
        'breakpoint',
        'color-multiply',
        'color',
        'control-height',
        'control-icon-transition',
        'control-slim-height',
        'control-vertical-padding',
        'duration',
        'easing',
        'em',
        'filter',
        'font-family',
        'font-size',
        'layout-width',
        'line-height',
        'map-extend',
        'mobile-nav-width',
        'ms-high-contrast-color',
        'nav-min-window-corrected',
        'px',
        'rem',
        'shadow',
        'spacing',
        'thumbnail-size',
        'top-bar-height',
        'z-index',
      ],
      {severity: 'warning'},
    ],
    'property-disallowed-list': [
      [
        'position',
        'grid',
        'flex',
        'flex-grow',
        'flex-shrink',
        'flex-basis',
        'justify-content',
        'align-items',
        'grid-row',
        'grid-row-start',
        'grid-row-end',
        'grid-column',
        'grid-column-start',
        'grid-column-end',
        'grid-template',
        'grid-template-areas',
        'grid-template-rows',
        'grid-template-columns',
        'grid-area',
        'display',
      ],
      {severity: 'warning'},
    ],
    'unit-disallowed-list': [
      ['px', 'rem', 'em', 's', 'ms'],
      {severity: 'warning'},
    ],
    'scss/function-color-relative': [true, {severity: 'warning'}],
    'stylelint-polaris/global-disallowed-list': [
      [
        // Legacy Scss mixins
        /@include after-topbar-sheet/,
        /@include base-button-disabled/,
        /@include breakpoint-after/,
        /@include breakpoint-before/,
        /@include button-base/,
        /@include button-filled/,
        /@include button-full-width/,
        /@include button-outline-disabled/,
        /@include button-outline/,
        /@include color-icon/,
        /@include control-backdrop/,
        /@include focus-ring/,
        /@include frame-when-nav-displayed/,
        /@include frame-when-nav-hidden/,
        /@include frame-with-nav-when-not-max-width/,
        /@include hidden-when-printing/,
        /@include high-contrast-border/,
        /@include high-contrast-button-outline/,
        /@include high-contrast-outline/,
        /@include icon-size/,
        /@include layout-flex-fix/,
        /@include list-selected-indicator/,
        /@include no-focus-ring/,
        /@include page-actions-layout/,
        /@include page-content-breakpoint-after/,
        /@include page-content-breakpoint-before/,
        /@include page-content-layout/,
        /@include page-content-when-fully-condensed/,
        /@include page-content-when-layout-not-stacked/,
        /@include page-content-when-layout-stacked/,
        /@include page-content-when-not-fully-condensed/,
        /@include page-content-when-not-partially-condensed/,
        /@include page-content-when-partially-condensed/,
        /@include page-header-has-navigation/,
        /@include page-header-has-secondary-actions/,
        /@include page-header-layout/,
        /@include page-header-without-navigation/,
        /@include page-layout/,
        /@include page-padding-not-fully-condensed/,
        /@include page-padding-not-partially-condensed/,
        /@include page-title-layout/,
        /@include page-when-not-max-width/,
        /@include plain-button-backdrop/,
        /@include print-hidden/,
        /@include range-thumb-selectors/,
        /@include range-track-selectors/,
        /@include recolor-icon/,
        /@include safe-area-for/,
        /@include skeleton-content/,
        /@include skeleton-page-header-layout/,
        /@include skeleton-page-secondary-actions-layout/,
        /@include skeleton-shimmer/,
        /@include state/,
        /@include text-breakword/,
        /@include text-emphasis-normal/,
        /@include text-emphasis-strong/,
        /@include text-emphasis-subdued/,
        /@include text-style-body/,
        /@include text-style-button-large/,
        /@include text-style-button/,
        /@include text-style-caption/,
        /@include text-style-display-large/,
        /@include text-style-display-medium/,
        /@include text-style-display-small/,
        /@include text-style-display-x-large/,
        /@include text-style-heading/,
        /@include text-style-input/,
        /@include text-style-subheading/,
        /@include truncate/,
        /@include unstyled-button/,
        /@include unstyled-input/,
        /@include unstyled-link/,
        /@include unstyled-list/,
        /@include visually-hidden/,
        /@include when-not-printing/,
        /@include when-printing/,
        /@include when-typography-condensed/,
        /@include when-typography-not-condensed/,
        // Legacy custom properties
        /--p-button-font/,
        /--p-badge-font/,
        /--p-override-loading-z-index/,
        /--p-override-none/,
        /--p-override-transparent/,
        /--p-override-one/,
        /--p-override-visible/,
        /--p-override-zero/,
        /--p-non-null-content/,
        /--p-badge-mix-blend-mode/,
        /--p-range-slider-thumb-scale/,
        /--p-duration-1-0-0/,
        /--p-duration-1-5-0/,
        /--p-border-radius-base/,
        /--p-border-radius-wide/,
        /--p-border-radius-full/,
        /--p-text-field-focus-ring-border-radius/,
        /--p-card-shadow/,
        /--p-popover-shadow/,
        /--p-modal-shadow/,
        /--p-top-bar-shadow/,
        /--p-button-drop-shadow/,
        /--p-button-inner-shadow/,
        /--p-button-pressed-inner-shadow/,
        /--p-control-border-width/,
        /--p-thin-border-subdued/,
        /--p-banner-border-default/,
        /--p-banner-border-success/,
        /--p-banner-border-highlight/,
        /--p-banner-border-warning/,
        /--p-banner-border-critical/,
        /--p-button-group-item-spacing/,
        /--p-choice-margin/,
        /--p-text-field-spinner-offset/,
        /--p-text-field-focus-ring-offset/,
        /--p-icon-size/,
        /--p-range-slider-thumb-size-base/,
        /--p-choice-size/,
        /--p-range-slider-thumb-size-active/,
        // Other warnings
        / \* \$/,
        /\$actions-vertical-spacing/,
        /\$base-font-size/,
        /\$border-radius-data/,
        /\$border-width-data/,
        /\$borders-data/,
        /\$color-filter-palette-data/,
        /\$color-palette-data/,
        /\$default-browser-font-size/,
        /\$duration-data/,
        /\$easing-data/,
        /\$fixed-element-stacking-order/,
        /\$font-family-data/,
        /\$font-size-data/,
        /\$global-elements/,
        /\$large-thumbnail-size/,
        /\$layout-width-data/,
        /\$line-height-data/,
        /\$medium-thumbnail-size/,
        /\$navigation-width/,
        /\$polaris-colors/,
        /\$polaris-duration-map/,
        /\$polaris-spacing/,
        /\$shadows-data/,
        /\$skeleton-shimmer-duration/,
        /\$small-thumbnail-size/,
        /\$spacing-data/,
        /\$thumbnail-sizes/,
        /\$typography-condensed/,
        /\$typography-condensed/,
      ],
      {severity: 'warning'},
    ],
  },
};
