/**
 * Stylelint config to ensure compliance with Polaris and improve coverage.
 */

/**
 * @type {import('stylelint').Config}
 */
module.exports = {
  plugins: [
    'stylelint-scss',
    '../plugins/at-rule-disallowed-list',
    '../plugins/global-disallowed-list',
  ],
  rules: {
    'at-rule-disallowed-list': [['keyframes'], {severity: 'warning'}],
    'color-named': ['never', {severity: 'warning'}],
    'color-no-hex': [true, {severity: 'warning'}],
    'declaration-property-value-disallowed-list': [
      {
        display: ['grid', 'flex'],
        top: [/(?!var\(--p-).+$/],
        bottom: [/(?!var\(--p-).+$/],
        left: [/(?!var\(--p-).+$/],
        right: [/(?!var\(--p-).+$/],
        width: [/(?!var\(--p-).+$/],
        height: [/(?!var\(--p-).+$/],
        // Allow `0`, `1`, values between 0 and 1 (limit 2 decimal places), and custom properties
        // https://regex101.com/r/kIlVrQ/1
        opacity: [/(?!0|1)\d$|^\d{2,}|^[1-9]+\.|^\d+\.\d+\.|^0\.\d{3,}/],
        'z-index': [/(?!var\(--p-).+$/],
        'font-weight': [/(\$.*|[0-9]+)/],
      },
      {severity: 'warning'},
    ],
    'function-disallowed-list': [
      [
        'brightness',
        'contrast',
        'hue-rotate',
        'hsl',
        'hsla',
        'invert',
        'rgb',
        'rgba',
        'sepia',
        // Include Sass namespace
        // https://regex101.com/r/UdW0oV/1
        /([\w-]+\.)?available-names/,
        /([\w-]+\.)?border-radius/,
        /([\w-]+\.)?border-width/,
        /([\w-]+\.)?border/,
        /([\w-]+\.)?breakpoint/,
        /([\w-]+\.)?color-multiply/,
        /([\w-]+\.)?color/,
        /([\w-]+\.)?control-height/,
        /([\w-]+\.)?control-icon-transition/,
        /([\w-]+\.)?control-slim-height/,
        /([\w-]+\.)?control-vertical-padding/,
        /([\w-]+\.)?duration/,
        /([\w-]+\.)?easing/,
        /([\w-]+\.)?em/,
        /([\w-]+\.)?filter/,
        /([\w-]+\.)?font-family/,
        /([\w-]+\.)?font-size/,
        /([\w-]+\.)?layout-width/,
        /([\w-]+\.)?line-height/,
        /([\w-]+\.)?map-extend/,
        /([\w-]+\.)?mobile-nav-width/,
        /([\w-]+\.)?ms-high-contrast-color/,
        /([\w-]+\.)?nav-min-window-corrected/,
        /([\w-]+\.)?px/,
        /([\w-]+\.)?rem/,
        /([\w-]+\.)?shadow/,
        /([\w-]+\.)?spacing/,
        /([\w-]+\.)?thumbnail-size/,
        /([\w-]+\.)?top-bar-height/,
        /([\w-]+\.)?z-index/,
      ],
      {severity: 'warning'},
    ],
    'property-disallowed-list': [
      [
        'position',
        'grid',
        'flex',
        'flex-grow',
        'flex-shrink',
        'flex-basis',
        'justify-content',
        'align-items',
        'grid-row',
        'grid-row-start',
        'grid-row-end',
        'grid-column',
        'grid-column-start',
        'grid-column-end',
        'grid-template',
        'grid-template-areas',
        'grid-template-rows',
        'grid-template-columns',
        'grid-area',
        'display',
      ],
      {severity: 'warning'},
    ],
    'unit-disallowed-list': [
      ['px', 'rem', 'em', 's', 'ms'],
      {severity: 'warning'},
    ],
    'scss/function-color-relative': [true, {severity: 'warning'}],
    'stylelint-polaris/at-rule-disallowed-list': [
      {
        include: [
          // Legacy Scss mixins
          // https://regex101.com/r/UdW0oV/1
          /([\w-]+\.)?after-topbar-sheet($|\()/,
          /([\w-]+\.)?base-button-disabled($|\()/,
          /([\w-]+\.)?breakpoint-after($|\()/,
          /([\w-]+\.)?breakpoint-before($|\()/,
          /([\w-]+\.)?button-base($|\()/,
          /([\w-]+\.)?button-filled($|\()/,
          /([\w-]+\.)?button-full-width($|\()/,
          /([\w-]+\.)?button-outline-disabled($|\()/,
          /([\w-]+\.)?button-outline($|\()/,
          /([\w-]+\.)?color-icon($|\()/,
          /([\w-]+\.)?control-backdrop($|\()/,
          /([\w-]+\.)?focus-ring($|\()/,
          /([\w-]+\.)?frame-when-nav-displayed($|\()/,
          /([\w-]+\.)?frame-when-nav-hidden($|\()/,
          /([\w-]+\.)?frame-with-nav-when-not-max-width($|\()/,
          /([\w-]+\.)?hidden-when-printing($|\()/,
          /([\w-]+\.)?high-contrast-border($|\()/,
          /([\w-]+\.)?high-contrast-button-outline($|\()/,
          /([\w-]+\.)?high-contrast-outline($|\()/,
          /([\w-]+\.)?icon-size($|\()/,
          /([\w-]+\.)?layout-flex-fix($|\()/,
          /([\w-]+\.)?list-selected-indicator($|\()/,
          /([\w-]+\.)?no-focus-ring($|\()/,
          /([\w-]+\.)?page-actions-layout($|\()/,
          /([\w-]+\.)?page-content-breakpoint-after($|\()/,
          /([\w-]+\.)?page-content-breakpoint-before($|\()/,
          /([\w-]+\.)?page-content-layout($|\()/,
          /([\w-]+\.)?page-content-when-fully-condensed($|\()/,
          /([\w-]+\.)?page-content-when-layout-not-stacked($|\()/,
          /([\w-]+\.)?page-content-when-layout-stacked($|\()/,
          /([\w-]+\.)?page-content-when-not-fully-condensed($|\()/,
          /([\w-]+\.)?page-content-when-not-partially-condensed($|\()/,
          /([\w-]+\.)?page-content-when-partially-condensed($|\()/,
          /([\w-]+\.)?page-header-has-navigation($|\()/,
          /([\w-]+\.)?page-header-has-secondary-actions($|\()/,
          /([\w-]+\.)?page-header-layout($|\()/,
          /([\w-]+\.)?page-header-without-navigation($|\()/,
          /([\w-]+\.)?page-layout($|\()/,
          /([\w-]+\.)?page-padding-not-fully-condensed($|\()/,
          /([\w-]+\.)?page-padding-not-partially-condensed($|\()/,
          /([\w-]+\.)?page-title-layout($|\()/,
          /([\w-]+\.)?page-when-not-max-width($|\()/,
          /([\w-]+\.)?plain-button-backdrop($|\()/,
          /([\w-]+\.)?print-hidden($|\()/,
          /([\w-]+\.)?range-thumb-selectors($|\()/,
          /([\w-]+\.)?range-track-selectors($|\()/,
          /([\w-]+\.)?recolor-icon($|\()/,
          /([\w-]+\.)?safe-area-for($|\()/,
          /([\w-]+\.)?skeleton-content($|\()/,
          /([\w-]+\.)?skeleton-page-header-layout($|\()/,
          /([\w-]+\.)?skeleton-page-secondary-actions-layout($|\()/,
          /([\w-]+\.)?skeleton-shimmer($|\()/,
          /([\w-]+\.)?state($|\()/,
          /([\w-]+\.)?text-breakword($|\()/,
          /([\w-]+\.)?text-emphasis-normal($|\()/,
          /([\w-]+\.)?text-emphasis-strong($|\()/,
          /([\w-]+\.)?text-emphasis-subdued($|\()/,
          /([\w-]+\.)?text-style-body($|\()/,
          /([\w-]+\.)?text-style-button-large($|\()/,
          /([\w-]+\.)?text-style-button($|\()/,
          /([\w-]+\.)?text-style-caption($|\()/,
          /([\w-]+\.)?text-style-display-large($|\()/,
          /([\w-]+\.)?text-style-display-medium($|\()/,
          /([\w-]+\.)?text-style-display-small($|\()/,
          /([\w-]+\.)?text-style-display-x-large($|\()/,
          /([\w-]+\.)?text-style-heading($|\()/,
          /([\w-]+\.)?text-style-input($|\()/,
          /([\w-]+\.)?text-style-subheading($|\()/,
          /([\w-]+\.)?truncate($|\()/,
          /([\w-]+\.)?unstyled-button($|\()/,
          /([\w-]+\.)?unstyled-input($|\()/,
          /([\w-]+\.)?unstyled-link($|\()/,
          /([\w-]+\.)?unstyled-list($|\()/,
          /([\w-]+\.)?visually-hidden($|\()/,
          /([\w-]+\.)?when-not-printing($|\()/,
          /([\w-]+\.)?when-printing($|\()/,
          /([\w-]+\.)?when-typography-condensed($|\()/,
          /([\w-]+\.)?when-typography-not-condensed($|\()/,
        ],
      },
      {severity: 'warning'},
    ],
    'stylelint-polaris/global-disallowed-list': [
      [
        // Legacy custom properties
        /--p-button-font/,
        /--p-badge-font/,
        /--p-override-loading-z-index/,
        /--p-override-none/,
        /--p-override-transparent/,
        /--p-override-one/,
        /--p-override-visible/,
        /--p-override-zero/,
        /--p-non-null-content/,
        /--p-badge-mix-blend-mode/,
        /--p-range-slider-thumb-scale/,
        /--p-duration-1-0-0/,
        /--p-duration-1-5-0/,
        /--p-border-radius-base/,
        /--p-border-radius-wide/,
        /--p-border-radius-full/,
        /--p-text-field-focus-ring-border-radius/,
        /--p-card-shadow/,
        /--p-popover-shadow/,
        /--p-modal-shadow/,
        /--p-top-bar-shadow/,
        /--p-button-drop-shadow/,
        /--p-button-inner-shadow/,
        /--p-button-pressed-inner-shadow/,
        /--p-control-border-width/,
        /--p-thin-border-subdued/,
        /--p-banner-border-default/,
        /--p-banner-border-success/,
        /--p-banner-border-highlight/,
        /--p-banner-border-warning/,
        /--p-banner-border-critical/,
        /--p-button-group-item-spacing/,
        /--p-choice-margin/,
        /--p-text-field-spinner-offset/,
        /--p-text-field-focus-ring-offset/,
        /--p-icon-size/,
        /--p-range-slider-thumb-size-base/,
        /--p-choice-size/,
        /--p-range-slider-thumb-size-active/,
        // Other warnings
        / \* \$/,
        /\$actions-vertical-spacing/,
        /\$base-font-size/,
        /\$border-radius-data/,
        /\$border-width-data/,
        /\$borders-data/,
        /\$color-filter-palette-data/,
        /\$color-palette-data/,
        /\$default-browser-font-size/,
        /\$duration-data/,
        /\$easing-data/,
        /\$fixed-element-stacking-order/,
        /\$font-family-data/,
        /\$font-size-data/,
        /\$global-elements/,
        /\$large-thumbnail-size/,
        /\$layout-width-data/,
        /\$line-height-data/,
        /\$medium-thumbnail-size/,
        /\$navigation-width/,
        /\$polaris-colors/,
        /\$polaris-duration-map/,
        /\$polaris-spacing/,
        /\$shadows-data/,
        /\$skeleton-shimmer-duration/,
        /\$small-thumbnail-size/,
        /\$spacing-data/,
        /\$thumbnail-sizes/,
        /\$typography-condensed/,
        /\$typography-condensed/,
      ],
      {severity: 'warning'},
    ],
  },
};
