/**
 * Stylelint config to ensure compliance with Polaris and improve coverage.
 */

/**
 * @type {import('stylelint').Config}
 */
module.exports = {
  plugins: [
    'stylelint-scss',
    '../plugins/at-rule-disallowed-list',
    '../plugins/global-disallowed-list',
  ],
  rules: {
    'at-rule-disallowed-list': [['keyframes'], {severity: 'warning'}],
    'color-named': ['never', {severity: 'warning'}],
    'color-no-hex': [true, {severity: 'warning'}],
    'declaration-property-value-disallowed-list': [
      {
        display: ['grid', 'flex'],
        top: [/^(?!var\(--p-).+$/],
        bottom: [/^(?!var\(--p-).+$/],
        left: [/^(?!var\(--p-).+$/],
        right: [/^(?!var\(--p-).+$/],
        width: [/^(?!var\(--p-).+$/],
        height: [/^(?!var\(--p-).+$/],
        // Allow `0`, `1`, values between 0 and 1 (limit 2 decimal places), and custom properties
        // https://regex101.com/r/kIlVrQ/1
        opacity: [/^(?!0|1)\d$|^\d{2,}|^[1-9]+\.|^\d+\.\d+\.|^0\.\d{3,}/],
        'z-index': [/^(?!var\(--p-).+$/],
        'font-weight': [/(\$.*|[0-9]+)/],
      },
      {severity: 'warning'},
    ],
    'function-disallowed-list': [
      [
        'brightness',
        'contrast',
        'hue-rotate',
        'hsl',
        'hsla',
        'invert',
        'rgb',
        'rgba',
        'sepia',
        'available-names',
        'border-radius',
        'border-width',
        'border',
        'breakpoint',
        'color-multiply',
        'color',
        'control-height',
        'control-icon-transition',
        'control-slim-height',
        'control-vertical-padding',
        'duration',
        'easing',
        'em',
        'filter',
        'font-family',
        'font-size',
        'layout-width',
        'line-height',
        'map-extend',
        'mobile-nav-width',
        'ms-high-contrast-color',
        'nav-min-window-corrected',
        'px',
        'rem',
        'shadow',
        'spacing',
        'thumbnail-size',
        'top-bar-height',
        'z-index',
      ],
      {severity: 'warning'},
    ],
    'property-disallowed-list': [
      [
        'position',
        'grid',
        'flex',
        'flex-grow',
        'flex-shrink',
        'flex-basis',
        'justify-content',
        'align-items',
        'grid-row',
        'grid-row-start',
        'grid-row-end',
        'grid-column',
        'grid-column-start',
        'grid-column-end',
        'grid-template',
        'grid-template-areas',
        'grid-template-rows',
        'grid-template-columns',
        'grid-area',
        'display',
      ],
      {severity: 'warning'},
    ],
    'unit-disallowed-list': [
      ['px', 'rem', 'em', 's', 'ms'],
      {severity: 'warning'},
    ],
    'scss/function-color-relative': [true, {severity: 'warning'}],
    'stylelint-polaris/at-rule-disallowed-list': [
      {
        include: [
          // Legacy Scss mixins
          // https://regex101.com/r/PJYwuP/1
          /^after-topbar-sheet($|\()/,
          /^base-button-disabled($|\()/,
          /^breakpoint-after($|\()/,
          /^breakpoint-before($|\()/,
          /^button-base($|\()/,
          /^button-filled($|\()/,
          /^button-full-width($|\()/,
          /^button-outline-disabled($|\()/,
          /^button-outline($|\()/,
          /^color-icon($|\()/,
          /^control-backdrop($|\()/,
          /^focus-ring($|\()/,
          /^frame-when-nav-displayed($|\()/,
          /^frame-when-nav-hidden($|\()/,
          /^frame-with-nav-when-not-max-width($|\()/,
          /^hidden-when-printing($|\()/,
          /^high-contrast-border($|\()/,
          /^high-contrast-button-outline($|\()/,
          /^high-contrast-outline($|\()/,
          /^icon-size($|\()/,
          /^layout-flex-fix($|\()/,
          /^list-selected-indicator($|\()/,
          /^no-focus-ring($|\()/,
          /^page-actions-layout($|\()/,
          /^page-content-breakpoint-after($|\()/,
          /^page-content-breakpoint-before($|\()/,
          /^page-content-layout($|\()/,
          /^page-content-when-fully-condensed($|\()/,
          /^page-content-when-layout-not-stacked($|\()/,
          /^page-content-when-layout-stacked($|\()/,
          /^page-content-when-not-fully-condensed($|\()/,
          /^page-content-when-not-partially-condensed($|\()/,
          /^page-content-when-partially-condensed($|\()/,
          /^page-header-has-navigation($|\()/,
          /^page-header-has-secondary-actions($|\()/,
          /^page-header-layout($|\()/,
          /^page-header-without-navigation($|\()/,
          /^page-layout($|\()/,
          /^page-padding-not-fully-condensed($|\()/,
          /^page-padding-not-partially-condensed($|\()/,
          /^page-title-layout($|\()/,
          /^page-when-not-max-width($|\()/,
          /^plain-button-backdrop($|\()/,
          /^print-hidden($|\()/,
          /^range-thumb-selectors($|\()/,
          /^range-track-selectors($|\()/,
          /^recolor-icon($|\()/,
          /^safe-area-for($|\()/,
          /^skeleton-content($|\()/,
          /^skeleton-page-header-layout($|\()/,
          /^skeleton-page-secondary-actions-layout($|\()/,
          /^skeleton-shimmer($|\()/,
          /^state($|\()/,
          /^text-breakword($|\()/,
          /^text-emphasis-normal($|\()/,
          /^text-emphasis-strong($|\()/,
          /^text-emphasis-subdued($|\()/,
          /^text-style-body($|\()/,
          /^text-style-button-large($|\()/,
          /^text-style-button($|\()/,
          /^text-style-caption($|\()/,
          /^text-style-display-large($|\()/,
          /^text-style-display-medium($|\()/,
          /^text-style-display-small($|\()/,
          /^text-style-display-x-large($|\()/,
          /^text-style-heading($|\()/,
          /^text-style-input($|\()/,
          /^text-style-subheading($|\()/,
          /^truncate($|\()/,
          /^unstyled-button($|\()/,
          /^unstyled-input($|\()/,
          /^unstyled-link($|\()/,
          /^unstyled-list($|\()/,
          /^visually-hidden($|\()/,
          /^when-not-printing($|\()/,
          /^when-printing($|\()/,
          /^when-typography-condensed($|\()/,
          /^when-typography-not-condensed($|\()/,
        ],
      },
      {severity: 'warning'},
    ],
    'stylelint-polaris/global-disallowed-list': [
      [
        // Legacy custom properties
        /--p-button-font/,
        /--p-badge-font/,
        /--p-override-loading-z-index/,
        /--p-override-none/,
        /--p-override-transparent/,
        /--p-override-one/,
        /--p-override-visible/,
        /--p-override-zero/,
        /--p-non-null-content/,
        /--p-badge-mix-blend-mode/,
        /--p-range-slider-thumb-scale/,
        /--p-duration-1-0-0/,
        /--p-duration-1-5-0/,
        /--p-border-radius-base/,
        /--p-border-radius-wide/,
        /--p-border-radius-full/,
        /--p-text-field-focus-ring-border-radius/,
        /--p-card-shadow/,
        /--p-popover-shadow/,
        /--p-modal-shadow/,
        /--p-top-bar-shadow/,
        /--p-button-drop-shadow/,
        /--p-button-inner-shadow/,
        /--p-button-pressed-inner-shadow/,
        /--p-control-border-width/,
        /--p-thin-border-subdued/,
        /--p-banner-border-default/,
        /--p-banner-border-success/,
        /--p-banner-border-highlight/,
        /--p-banner-border-warning/,
        /--p-banner-border-critical/,
        /--p-button-group-item-spacing/,
        /--p-choice-margin/,
        /--p-text-field-spinner-offset/,
        /--p-text-field-focus-ring-offset/,
        /--p-icon-size/,
        /--p-range-slider-thumb-size-base/,
        /--p-choice-size/,
        /--p-range-slider-thumb-size-active/,
        // Other warnings
        / \* \$/,
        /\$actions-vertical-spacing/,
        /\$base-font-size/,
        /\$border-radius-data/,
        /\$border-width-data/,
        /\$borders-data/,
        /\$color-filter-palette-data/,
        /\$color-palette-data/,
        /\$default-browser-font-size/,
        /\$duration-data/,
        /\$easing-data/,
        /\$fixed-element-stacking-order/,
        /\$font-family-data/,
        /\$font-size-data/,
        /\$global-elements/,
        /\$large-thumbnail-size/,
        /\$layout-width-data/,
        /\$line-height-data/,
        /\$medium-thumbnail-size/,
        /\$navigation-width/,
        /\$polaris-colors/,
        /\$polaris-duration-map/,
        /\$polaris-spacing/,
        /\$shadows-data/,
        /\$skeleton-shimmer-duration/,
        /\$small-thumbnail-size/,
        /\$spacing-data/,
        /\$thumbnail-sizes/,
        /\$typography-condensed/,
        /\$typography-condensed/,
      ],
      {severity: 'warning'},
    ],
  },
};
