import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { parseMarkdown } from "../utils/markdown.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const componentsDir = path.join(__dirname, "../../content/components");
const examplesDir = path.join(__dirname, "../pages/examples");
const componentDirectories = fs.readdirSync(componentsDir, "utf-8");

const getExamplePage = ({ component, contents, filename }) => `
/**
 * This file is automatically generated from: polaris.shopify.com/src/scripts/generate-examples.mjs
 * The source of the example is from: polaris.shopify.com/src/content/${component}/${filename}
 */

${contents}

import PolarisExample from '../../components/PolarisExample';

export function ComponentExample() {
  return (
    <PolarisExample>
      <Example />
    </PolarisExample>
  )
}

export default ComponentExample
`;

// Delete examples dir
if (fs.existsSync(examplesDir)) {
  fs.rmSync(examplesDir, { recursive: true });
}

fs.mkdirSync(examplesDir);

// Read the components
componentDirectories.forEach((directory) => {
  const directoryPath = path.join(componentsDir, directory);
  const directoryContents = fs.readdirSync(directoryPath, "utf-8");
  const examples = directoryContents.filter((name) => name.endsWith(".tsx"));

  // Read the examples
  examples.forEach((exampleFilename) => {
    const exampleFilePath = path.join(directoryPath, exampleFilename);
    const contents = fs.readFileSync(exampleFilePath, "utf-8");

    // Format example content
    const examplePage = getExamplePage({
      contents,
      component: directory,
      filename: exampleFilename,
    });

    // Write example content
    const outputPath = path.join(
      examplesDir,
      `${directory}-${exampleFilename}`
    );

    fs.writeFileSync(outputPath, examplePage);
  });
});
