export declare const colorPurpleText = "rgb(80, 73, 90)";
export declare const colorPurpleDarker = "rgb(35, 0, 81)";
export declare const colorPurpleDark = "rgb(80, 36, 143)";
export declare const colorPurple = "rgb(156, 106, 222)";
export declare const colorPurpleLight = "rgb(227, 208, 255)";
export declare const colorPurpleLighter = "rgb(246, 240, 253)";
export declare const colorIndigoText = "rgb(62, 65, 85)";
export declare const colorIndigoDarker = "rgb(0, 6, 57)";
export declare const colorIndigoDark = "rgb(32, 46, 120)";
export declare const colorIndigo = "rgb(92, 106, 196)";
export declare const colorIndigoLight = "rgb(179, 188, 245)";
export declare const colorIndigoLighter = "rgb(244, 245, 250)";
export declare const colorBlueText = "rgb(62, 78, 87)";
export declare const colorBlueDarker = "rgb(0, 20, 41)";
export declare const colorBlueDark = "rgb(8, 78, 138)";
export declare const colorBlue = "rgb(0, 111, 187)";
export declare const colorBlueLight = "rgb(180, 225, 250)";
export declare const colorBlueLighter = "rgb(235, 245, 250)";
export declare const colorTealText = "rgb(64, 83, 82)";
export declare const colorTealDarker = "rgb(0, 49, 53)";
export declare const colorTealDark = "rgb(0, 132, 142)";
export declare const colorTeal = "rgb(71, 193, 191)";
export declare const colorTealLight = "rgb(183, 236, 236)";
export declare const colorTealLighter = "rgb(224, 245, 245)";
export declare const colorGreenText = "rgb(65, 79, 62)";
export declare const colorGreenDarker = "rgb(23, 54, 48)";
export declare const colorGreenDark = "rgb(16, 128, 67)";
export declare const colorGreen = "rgb(80, 184, 60)";
export declare const colorGreenLight = "rgb(187, 229, 179)";
export declare const colorGreenLighter = "rgb(227, 241, 223)";
export declare const colorYellowText = "rgb(89, 81, 48)";
export declare const colorYellowDarker = "rgb(87, 59, 0)";
export declare const colorYellowDark = "rgb(138, 97, 22)";
export declare const colorYellow = "rgb(238, 194, 0)";
export declare const colorYellowLight = "rgb(255, 234, 138)";
export declare const colorYellowLighter = "rgb(252, 241, 205)";
export declare const colorOrangeText = "rgb(89, 68, 48)";
export declare const colorOrangeDarker = "rgb(74, 21, 4)";
export declare const colorOrangeDark = "rgb(192, 87, 23)";
export declare const colorOrange = "rgb(244, 147, 66)";
export declare const colorOrangeLight = "rgb(255, 197, 139)";
export declare const colorOrangeLighter = "rgb(252, 235, 219)";
export declare const colorRedText = "rgb(88, 60, 53)";
export declare const colorRedDarker = "rgb(51, 1, 1)";
export declare const colorRedDark = "rgb(191, 7, 17)";
export declare const colorRed = "rgb(222, 54, 24)";
export declare const colorRedLight = "rgb(254, 173, 154)";
export declare const colorRedLighter = "rgb(251, 234, 229)";
export declare const colorInk = "rgb(33, 43, 54)";
export declare const colorInkLight = "rgb(69, 79, 91)";
export declare const colorInkLighter = "rgb(99, 115, 129)";
export declare const colorInkLightest = "rgb(145, 158, 171)";
export declare const colorSkyDark = "rgb(196, 205, 213)";
export declare const colorSky = "rgb(223, 227, 232)";
export declare const colorSkyLight = "rgb(244, 246, 248)";
export declare const colorSkyLighter = "rgb(249, 250, 251)";
export declare const colorBlack = "rgb(0, 0, 0)";
export declare const colorWhite = "rgb(255, 255, 255)";
export declare const durationNone = 0;
export declare const durationFast = 100;
export declare const durationBase = 200;
export declare const durationSlow = 300;
export declare const durationSlower = 400;
export declare const durationSlowest = 500;
export declare const spacingNone = 0;
export declare const spacingExtraTight = "4px";
export declare const spacingTight = "8px";
export declare const spacingBaseTight = "12px";
export declare const spacingBase = "16px";
export declare const spacingLoose = "20px";
export declare const spacingExtraLoose = "32px";
export declare const fontStackBase = "-apple-system, BlinkMacSystemFont, 'San Francisco', 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif";
export declare const fontStackMonospace = "Monaco, Consolas, 'Lucida Console', monospace";
declare const _default: {
    colorPurpleText: string;
    colorPurpleDarker: string;
    colorPurpleDark: string;
    colorPurple: string;
    colorPurpleLight: string;
    colorPurpleLighter: string;
    colorIndigoText: string;
    colorIndigoDarker: string;
    colorIndigoDark: string;
    colorIndigo: string;
    colorIndigoLight: string;
    colorIndigoLighter: string;
    colorBlueText: string;
    colorBlueDarker: string;
    colorBlueDark: string;
    colorBlue: string;
    colorBlueLight: string;
    colorBlueLighter: string;
    colorTealText: string;
    colorTealDarker: string;
    colorTealDark: string;
    colorTeal: string;
    colorTealLight: string;
    colorTealLighter: string;
    colorGreenText: string;
    colorGreenDarker: string;
    colorGreenDark: string;
    colorGreen: string;
    colorGreenLight: string;
    colorGreenLighter: string;
    colorYellowText: string;
    colorYellowDarker: string;
    colorYellowDark: string;
    colorYellow: string;
    colorYellowLight: string;
    colorYellowLighter: string;
    colorOrangeText: string;
    colorOrangeDarker: string;
    colorOrangeDark: string;
    colorOrange: string;
    colorOrangeLight: string;
    colorOrangeLighter: string;
    colorRedText: string;
    colorRedDarker: string;
    colorRedDark: string;
    colorRed: string;
    colorRedLight: string;
    colorRedLighter: string;
    colorInk: string;
    colorInkLight: string;
    colorInkLighter: string;
    colorInkLightest: string;
    colorSkyDark: string;
    colorSky: string;
    colorSkyLight: string;
    colorSkyLighter: string;
    colorBlack: string;
    colorWhite: string;
    durationNone: number;
    durationFast: number;
    durationBase: number;
    durationSlow: number;
    durationSlower: number;
    durationSlowest: number;
    spacingNone: number;
    spacingExtraTight: string;
    spacingTight: string;
    spacingBaseTight: string;
    spacingBase: string;
    spacingLoose: string;
    spacingExtraLoose: string;
    fontStackBase: string;
    fontStackMonospace: string;
};
export default _default;
