import type { NextPage } from "next";
import Page from "../../components/Page";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <Page>
      <Head>
        <title>Polaris</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <p>Docs</p>
    </Page>
  );
};

export default Home;
