name: Automation
set: major
authors:
  - Adam Whitcroft
  - Joe Thomas
  - José Torre
description: Used to represent automation, or a task that can be automated.
keywords:
  - automation
  - cog
  - automated
  - gear
version: 1
date_added: 2019-10-07
date_modified: 2023-11-07
exclusive_use:
