name: Package
set: major
description: Used to represent a package or box that merchants can ship their products in.
keywords:
  - shipping
  - box
  - package
  - cardboard
authors:
  - N/A
  - Joe Thomas
version: 1
date_added: 2019-03-15
date_modified: 2023-06-23
exclusive_use:
