name: Product Reference
set: minor
description: Used to represent products referenced on other resources
keywords:
  - products
  - reference
  - metafields
authors:
  - Sai Nihas
  - Leina Leung
version: 1
date_added: 2023-01-12
date_modified: 2023-01-12
exclusive_use:
