name: Product unavailable
description: When a product has been deleted and is no longer available
keywords:
  - Product
authors:
  - Joe Thomas
date_added: 2024-06-21
date_modified: 2024-06-21
# Optional: fill exclusive_use if the icon should *only* be used
# in specific areas of the admin (such as “Orders”):
