name: Product remove
description: Used to represent an action to remove a product.
keywords:
  - remove
  - minus
  - product
authors:
  - Anthony Menecola
  - Joe Thomas
date_added: 2019-03-15
date_modified: 2023-06-23
