name: Products filled
description: Used to represent products or a price tag.
keywords:
  - tag
  - products
  - price
authors:
  - Joe Thomas
  - José Torre
date_added: 2023-07-06
date_modified: 2023-11-07
exclusive_use:
