name: Products
set: major
description: Used to represent products or a price tag.
keywords:
  - tag
  - products
  - price
authors:
  - Adam Whitcroft
  - Anthony Menecola
version: 2
date_added: 2019-03-15
date_modified: 2022-08-08
exclusive_use:
