name: Product Reference
description: Used to represent products referenced on other resources
keywords:
  - products
  - reference
  - metafields
authors:
  - Sai Nihas
  - Leina Leung
  - Joe Thomas
date_added: 2023-01-12
date_modified: 2023-06-23
exclusive_use:
