name: Product add
description: Used as an action to add a new product.
keywords:
  - add
  - product
  - price tag
authors:
  - Anthony Menecola
  - Joe Thomas
date_added: 2019-03-15
date_modified: 2023-06-23
