name: Product list
description: Used to represent a list of products.
keywords:
  - tag
  - products
  - price
  - list
authors:
  - Wanita Jana
  - Joe Thomas
date_added: 2024-01-29
date_modified: 2024-03-03
