name: Product returns
set: minor
description: Used to help direct merchants to returns page.
keywords:
  - return
  - product return
  - return page
  - arrow
authors:
  - Clara Petit
  - Joe Thomas
version: 1
date_added: 2020-07-08
date_modified: 2023-06-23
exclusive_use:
