name: products
set: major
description: Used to represent products or a price tag.
keywords:
  - tag
  - products
  - price
authors:
  - Adam Whitcroft
version: 1
date_added: 2019-03-15
date_modified: 2019-03-15
exclusive_use:
