name: ProductCostMajor
set: major
description: Used to represent the cost of a product
keywords:
  - product
  - cost
authors:
  - Adam Whitcroft
  - Anthony Menecola
version: 1
date_added: 2022-08-08
date_modified: 2022-08-08
exclusive_use:
