name: Product return
description: Used to help direct merchants to returns page.
keywords:
  - return
  - product return
  - return page
  - arrow
authors:
  - Clara Petit
  - Joe Thomas
date_added: 2020-07-08
date_modified: 2023-06-23
