name: Product cost
description: Used to represent the cost of a product
keywords:
  - product
  - cost
authors:
  - Adam Whitcroft
  - Anthony Menecola
  - Joe Thomas
date_added: 2022-08-08
date_modified: 2023-06-23
