name: Settings filled
set: minor
description: Used to represent settings or a configuration option.
keywords:
  - configure
  - settings
  - cog
authors:
  - Joe Thomas
version: 1
date_added: 2023-07-06
date_modified: 2023-07-06
exclusive_use:
