name: Settings filled
description: Used to represent settings or a configuration option.
keywords:
  - configure
  - settings
  - cog
authors:
  - Joe Thomas
date_added: 2023-07-06
date_modified: 2023-07-06
