name: Settings
set: minor
description: Used to represent settings or a configuration option.
keywords:
  - configure
  - settings
  - cog
authors:
  - Adam Whitcroft
  - Joe Thomas
version: 1
date_added: 2019-03-15
date_modified: 2023-06-23
exclusive_use:
