name: Settings
description: Used to represent settings or a configuration option.
keywords:
  - configure
  - settings
  - cog
authors:
  - Adam Whitcroft
  - Joe Thomas
date_added: 2019-03-15
date_modified: 2023-06-23
