import * as colors from '../colors-experimental';
import {size} from '../size';

import {createMetaTheme, createMetaThemePartial} from './utils';

export const metaThemeLightUpliftPartial = createMetaThemePartial({
  border: {
    // v12.0.0
    'border-radius-0': {value: size[0]},
    'border-radius-050': {value: size['050']},
    'border-radius-100': {value: size[100]},
    'border-radius-150': {value: size[150]},
    'border-radius-200': {value: size[200]},
    'border-radius-300': {value: size[300]},
    'border-radius-400': {value: size[400]},
    'border-radius-500': {value: size[500]},
    'border-radius-750': {value: size[750]},
    'border-width-0165': {value: size['0165']},
    'border-width-025': {value: size['025']},
    'border-width-050': {value: size['050']},
    'border-width-100': {value: size[100]},
  },
  color: {
    // v12.0.0
    'color-bg-surface': {value: colors.gray[1]},
    'color-bg-surface-secondary': {value: colors.gray[4]},
    'color-bg-surface-secondary-hover': {value: colors.gray[6]},
    'color-bg-surface-secondary-active': {value: colors.gray[7]},
    'color-bg-surface-tertiary': {value: colors.gray[5]},
    'color-bg-fill-tertiary': {value: colors.gray[8]},
    'color-bg-fill-tertiary-hover': {value: colors.gray[9]},
    'color-bg-fill-tertiary-active': {value: colors.gray[10]},
    'color-input-bg-surface': {value: colors.gray[2]},
    'color-input-bg-surface-hover': {value: colors.gray[3]},
    'color-input-bg-surface-active': {value: colors.gray[4]},
    'color-bg-surface-selected': {value: colors.gray[3]},
    'color-bg-fill-success': {value: colors.green[12]},
    'color-bg-fill-success-hover': {value: colors.green[13]},
    'color-bg-fill-success-active': {value: colors.green[14]},
    'color-bg-fill-success-secondary': {value: colors.green[3]},
    'color-bg-surface-success': {value: colors.green[3]},
    'color-bg-surface-success-hover': {value: colors.green[4]},
    'color-bg-surface-success-active': {value: colors.green[5]},
    'color-bg-fill-critical': {value: colors.red[12]},
    'color-bg-fill-critical-hover': {value: colors.red[13]},
    'color-bg-fill-critical-active': {value: colors.red[14]},
    'color-bg-fill-critical-secondary': {value: colors.red[6]},
    'color-bg-surface-critical': {value: colors.red[4]},
    'color-bg-surface-critical-hover': {value: colors.red[5]},
    'color-bg-surface-critical-active': {value: colors.red[6]},
    'color-bg-fill-caution': {value: colors.yellow[6]},
    'color-bg-fill-caution-secondary': {value: colors.yellow[4]},
    'color-bg-surface-caution': {value: colors.yellow[2]},
    'color-bg-surface-caution-hover': {value: colors.yellow[3]},
    'color-bg-surface-caution-active': {value: colors.yellow[4]},
    'color-bg-fill-info': {value: colors.azure[9]},
    'color-bg-fill-info-secondary': {value: colors.azure[4]},
    'color-bg-surface-info': {value: colors.azure[3]},
    'color-bg-surface-info-hover': {value: colors.azure[4]},
    'color-bg-surface-info-active': {value: colors.azure[6]},
    'color-bg-fill-warning': {value: colors.orange[9]},
    'color-bg-fill-warning-secondary': {value: colors.orange[7]},
    'color-bg-surface-warning': {value: colors.orange[3]},
    'color-bg-fill-magic': {value: colors.purple[12]},
    'color-bg-fill-magic-secondary': {value: colors.purple[6]},
    'color-bg-fill-magic-secondary-hover': {value: colors.purple[7]},
    'color-bg-fill-magic-secondary-active': {value: colors.purple[8]},
    'color-bg-surface-magic-hover': {value: colors.purple[4]},
    'color-bg-fill-secondary': {value: colors.gray[6]},
    'color-bg-fill-inverse': {value: colors.gray[15]},
    'color-bg-fill-inverse-hover': {value: colors.gray[14]},
    'color-bg-fill-inverse-active': {value: colors.gray[13]},
    'color-bg-surface-transparent': {value: colors.blackAlpha[1]},
    'color-bg-fill-transparent-hover': {value: colors.blackAlpha[5]},
    'color-bg-fill-transparent-active': {value: colors.blackAlpha[6]},
    'color-bg-fill-disabled': {value: colors.blackAlpha[5]},
    'color-bg-fill-transparent-secondary': {value: colors.blackAlpha[6]},
    'color-bg-fill-brand-disabled': {value: colors.blackAlpha[9]},
    'color-backdrop-bg': {value: colors.blackAlpha[14]},
    'color-avatar-bg-fill': {value: colors.gray[11]},
    'color-avatar-one-bg-fill': {value: colors.magenta[7]},
    'color-avatar-two-bg-fill': {value: colors.green[7]},
    'color-avatar-three-bg-fill': {value: colors.cyan[7]},
    'color-avatar-four-bg-fill': {value: colors.azure[7]},
    'color-avatar-five-bg-fill': {value: colors.rose[7]},
    'color-text-secondary': {value: colors.gray[13]},
    'color-text-emphasis': {value: colors.blue[13]},
    'color-text-emphasis-hover': {value: colors.blue[14]},
    'color-text-emphasis-active': {value: colors.blue[15]},
    'color-text-brand': {value: colors.gray[14]},
    'color-text-brand-hover': {value: colors.gray[15]},
    'color-text-info-on-bg-fill': {value: colors.azure[16]},
    'color-text-inverse-secondary': {value: colors.gray[11]},
    'color-avatar-text-on-bg-fill': {value: colors.gray[1]},
    'color-avatar-one-text-on-bg-fill': {value: colors.magenta[14]},
    'color-avatar-two-text-on-bg-fill': {value: colors.green[14]},
    'color-avatar-three-text-on-bg-fill': {value: colors.cyan[14]},
    'color-avatar-four-text-on-bg-fill': {value: colors.azure[14]},
    'color-avatar-five-text-on-bg-fill': {value: colors.rose[14]},
    'color-icon-secondary': {value: colors.gray[12]},
    'color-icon-emphasis': {value: colors.blue[13]},
    'color-icon-emphasis-hover': {value: colors.blue[14]},
    'color-icon-emphasis-active': {value: colors.blue[15]},
    'color-icon-brand': {value: colors.gray[16]},
    'color-border-secondary': {value: colors.gray[7]},
    'color-input-border': {value: colors.gray[12]},
    'color-input-border-hover': {value: colors.gray[13]},
    'color-input-border-active': {value: colors.gray[16]},
    'color-border-emphasis-hover': {value: colors.blue[14]},
    'color-border-emphasis-active': {value: colors.blue[15]},
    'color-border-focus': {value: colors.blue[13]},
    'color-border-brand': {value: colors.gray[8]},
    'color-border-critical-secondary': {value: colors.red[14]},
    'color-border-magic-secondary': {value: colors.purple[12]},
    // v11.0.0
    'color-bg-inverse': {value: colors.gray[16]},
    'color-bg-inset-strong': {value: colors.gray[15]},
    'color-bg-inverse-hover': {value: colors.gray[14]},
    'color-bg-inverse-active': {value: colors.gray[13]},
    'color-bg-strong-hover': {value: colors.gray[9]},
    'color-bg-strong-active': {value: colors.gray[10]},
    'color-bg-strong': {value: colors.gray[8]},
    'color-bg-subdued-active': {value: colors.gray[7]},
    'color-bg-disabled': {value: colors.gray[7]},
    'color-bg-interactive-disabled': {value: colors.gray[7]},
    'color-bg-app': {value: colors.gray[6]},
    'color-bg-app-hover': {value: colors.gray[2]},
    'color-bg-app-selected': {value: colors.gray[3]},
    'color-bg-active': {value: colors.gray[4]},
    'color-bg-subdued-hover': {value: colors.gray[6]},
    'color-bg-inset': {value: colors.gray[6]},
    'color-bg-hover': {value: colors.gray[3]},
    'color-bg-subdued': {value: colors.gray[4]},
    'color-bg-input': {value: colors.gray[1]},
    'color-bg': {value: colors.gray[1]},
    'color-bg-primary-active': {value: colors.gray[16]},
    'color-bg-primary-hover': {value: colors.gray[16]},
    'color-bg-primary': {value: colors.gray[15]},
    'color-bg-success-strong': {value: colors.green[12]},
    'color-bg-success': {value: colors.green[3]},
    'color-bg-primary-subdued-active': {value: colors.gray[6]},
    'color-bg-success-subdued': {value: colors.green[3]},
    'color-bg-primary-subdued-hover': {value: colors.gray[7]},
    'color-bg-success-subdued-hover': {value: colors.green[5]},
    'color-bg-primary-subdued': {value: colors.gray[8]},
    'color-bg-primary-subdued-selected': {value: colors.gray[6]},
    'color-bg-critical-strong-active': {value: colors.red[14]},
    'color-bg-critical-strong-hover': {value: colors.red[13]},
    'color-bg-critical-strong': {value: colors.red[12]},
    'color-bg-critical-subdued-active': {value: colors.red[6]},
    'color-bg-critical': {value: colors.red[6]},
    'color-bg-critical-subdued': {value: colors.red[4]},
    'color-bg-critical-subdued-hover': {value: colors.red[5]},
    'color-bg-caution-strong': {value: colors.yellow[6]},
    'color-bg-caution': {value: colors.yellow[4]},
    'color-bg-caution-subdued-active': {value: colors.yellow[4]},
    'color-bg-caution-subdued': {value: colors.yellow[2]},
    'color-bg-caution-subdued-hover': {value: colors.yellow[3]},
    'color-bg-info-strong': {value: colors.azure[9]},
    'color-bg-info-subdued-active': {value: colors.azure[6]},
    'color-bg-info': {value: colors.azure[4]},
    'color-bg-info-subdued': {value: colors.azure[3]},
    'color-bg-info-subdued-hover': {value: colors.azure[4]},
    'color-bg-interactive-active': {value: colors.gray[14]},
    'color-bg-interactive-hover': {value: colors.gray[15]},
    'color-bg-interactive': {value: colors.gray[16]},
    'color-bg-interactive-subdued-active': {value: colors.gray[6]},
    'color-bg-interactive-subdued-hover': {value: colors.gray[7]},
    'color-bg-interactive-subdued': {value: colors.gray[8]},
    'color-bg-interactive-selected': {value: colors.gray[6]},
    'color-bg-warning': {value: colors.orange[7]},
    'color-bg-magic-strong': {value: colors.purple[12]},
    'color-bg-magic-hover': {value: colors.purple[7]},
    'color-bg-magic-active': {value: colors.purple[8]},
    'color-bg-magic': {value: colors.purple[6]},
    'color-bg-magic-subdued-hover': {value: colors.purple[4]},
    'color-bg-magic-subdued-active': {value: colors.purple[6]},
    'color-bg-magic-subdued': {value: colors.purple[3]},
    'color-border-input-hover': {value: colors.gray[13]},
    'color-border-inverse': {value: colors.gray[13]},
    'color-border-strong-hover': {value: colors.gray[11]},
    'color-border-input': {value: colors.gray[12]},
    'color-border-hover': {value: colors.gray[10]},
    'color-border-strong': {value: colors.gray[10]},
    'color-border': {value: colors.gray[8]},
    'color-border-disabled': {value: colors.gray[7]},
    'color-border-subdued': {value: colors.gray[7]},
    'color-border-interactive-disabled': {value: colors.gray[7]},
    'color-border-primary': {value: colors.gray[8]},
    'color-border-success': {value: colors.green[5]},
    'color-border-success-subdued': {value: colors.green[5]},
    'color-border-critical-active': {value: colors.red[11]},
    'color-border-critical-hover': {value: colors.red[10]},
    'color-border-critical': {value: colors.red[9]},
    'color-border-critical-subdued': {value: colors.red[9]},
    'color-border-caution': {value: colors.yellow[5]},
    'color-border-caution-subdued': {value: colors.yellow[5]},
    'color-border-info': {value: colors.azure[9]},
    'color-border-info-subdued': {value: colors.azure[9]},
    'color-border-interactive-active': {value: colors.blue[15]},
    'color-border-interactive-hover': {value: colors.blue[14]},
    'color-border-interactive': {value: colors.blue[13]},
    'color-border-interactive-focus': {value: colors.blue[13]},
    'color-border-interactive-subdued': {value: colors.blue[13]},
    'color-border-magic-strong': {value: colors.purple[12]},
    'color-border-magic': {value: colors.purple[10]},
    'color-icon-hover': {value: colors.gray[15]},
    'color-icon': {value: colors.gray[14]},
    'color-icon-subdued': {value: colors.gray[12]},
    'color-icon-disabled': {value: colors.gray[10]},
    'color-icon-interactive-disabled': {value: colors.gray[10]},
    'color-icon-inverse': {value: colors.gray[8]},
    'color-icon-on-color': {value: colors.gray[1]},
    'color-icon-primary': {value: colors.gray[16]},
    'color-icon-success': {value: colors.green[12]},
    'color-icon-critical': {value: colors.red[11]},
    'color-icon-caution': {value: colors.yellow[11]},
    'color-icon-info': {value: colors.azure[11]},
    'color-icon-warning': {value: colors.orange[11]},
    'color-icon-interactive-active': {value: colors.blue[15]},
    'color-icon-interactive-hover': {value: colors.blue[14]},
    'color-icon-interactive': {value: colors.blue[13]},
    'color-icon-interactive-inverse': {value: colors.blue[8]},
    'color-icon-magic': {value: colors.purple[13]},
    'color-text': {value: colors.gray[15]},
    'color-text-subdued': {value: colors.gray[13]},
    'color-text-disabled': {value: colors.gray[11]},
    'color-text-interactive-disabled': {value: colors.gray[10]},
    'color-text-inverse-subdued': {value: colors.gray[10]},
    'color-text-inverse': {value: colors.gray[8]},
    'color-text-on-color': {value: colors.gray[1]},
    'color-text-success-strong': {value: colors.green[15]},
    'color-text-success': {value: colors.green[15]},
    'color-text-primary': {value: colors.gray[14]},
    'color-text-primary-hover': {value: colors.gray[14]},
    'color-text-critical-strong': {value: colors.red[14]},
    'color-text-critical-active': {value: colors.red[16]},
    'color-text-critical': {value: colors.red[14]},
    'color-text-caution-strong': {value: colors.yellow[15]},
    'color-text-caution': {value: colors.yellow[15]},
    'color-text-info-strong': {value: colors.azure[16]},
    'color-text-info': {value: colors.azure[14]},
    'color-text-warning-strong': {value: colors.orange[16]},
    'color-text-interactive-active': {value: colors.blue[15]},
    'color-text-interactive-hover': {value: colors.blue[14]},
    'color-text-interactive': {value: colors.blue[13]},
    'color-text-interactive-inverse': {value: colors.blue[8]},
    'color-text-magic-strong': {value: colors.purple[15]},
    'color-text-magic': {value: colors.purple[14]},
  },
  font: {
    // v12.0.0
    'font-size-275': {value: size[275]},
    'font-size-325': {value: size[325]},
    'font-size-350': {value: size[350]},
    'font-size-750': {value: size[750]},
    'font-size-900': {value: size[900]},
    'font-size-1000': {value: size[1000]},
    'font-line-height-300': {value: size[300]},
    'font-line-height-400': {value: size[400]},
    'font-line-height-500': {value: size[500]},
    'font-line-height-600': {value: size[600]},
    'font-line-height-700': {value: size[700]},
    'font-line-height-800': {value: size[800]},
    'font-line-height-1000': {value: size[1000]},
    'font-line-height-1200': {value: size[1200]},
    // v11.0.0
    'font-family-sans': {
      value:
        "'Inter', -apple-system, BlinkMacSystemFont, 'San Francisco', 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif",
    },
    'font-size-500': {value: '30px'},
    'font-size-600': {value: '36px'},
  },
  motion: {
    // v11.0.0
    'motion-ease-out': {value: 'cubic-bezier(0.19, 0.91, 0.38, 1)'},
  },
  space: {
    // v12.0.0
    'space-050': {value: size['050']},
    'space-100': {value: size[100]},
    'space-150': {value: size[150]},
    'space-200': {value: size[200]},
    'space-300': {value: size[300]},
    'space-400': {value: size[400]},
    'space-500': {value: size[500]},
    'space-600': {value: size[600]},
    'space-800': {value: size[800]},
    'space-1000': {value: size[1000]},
    'space-1200': {value: size[1200]},
    'space-1600': {value: size[1600]},
    'space-2000': {value: size[2000]},
    'space-2400': {value: size[2400]},
    'space-2800': {value: size[2800]},
    'space-3200': {value: size[3200]},
  },
  shadow: {
    // v11.0.0
    'shadow-inset-lg': {
      value:
        'inset -1px 0px 1px rgba(0, 0, 0, 0.2), inset 1px 0px 1px rgba(0, 0, 0, 0.2), inset 0px 2px 1px rgba(0, 0, 0, 0.6)',
    },
    'shadow-inset-md': {
      value:
        'inset -1px 0px 1px rgba(0, 0, 0, 0.12), inset 1px 0px 1px rgba(0, 0, 0, 0.12), inset 0px 2px 1px rgba(0, 0, 0, 0.2)',
    },
    'shadow-inset-sm': {
      value:
        'inset 0px 1px 1px rgba(0, 0, 0, 0.15), inset 0px 1px 2px rgba(255, 255, 255, 0.15)',
    },
    'shadow-xs': {value: '0px 1px 0px rgba(0, 0, 0, 0.07)'},
    'shadow-sm': {value: '0px 3px 1px -1px rgba(0, 0, 0, 0.07)'},
    'shadow-md': {value: '0px 4px 6px -2px rgba(0, 0, 0, 0.2)'},
    'shadow-lg': {value: '0px 8px 16px -4px rgba(0, 0, 0, 0.22)'},
    'shadow-xl': {value: '0px 12px 20px -8px rgba(0, 0, 0, 0.24)'},
    'shadow-2xl': {value: '0px 20px 20px -8px rgba(0, 0, 0, 0.28)'},
  },
});

export const metaThemeLightUplift = createMetaTheme(
  metaThemeLightUpliftPartial,
);
