import * as colors from '../colors-experimental';

import {createMetaThemeVariant, createMetaThemeVariantPartial} from './utils';

export const metaThemeLightUpliftPartial = createMetaThemeVariantPartial({
  motion: {
    'motion-ease-out': {value: 'cubic-bezier(0.19, 0.91, 0.38, 1)'},
  },
  font: {
    'font-family-sans': {
      value:
        "'Inter', -apple-system, BlinkMacSystemFont, 'San Francisco', 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif",
    },
    'font-size-500': {value: '30px'},
    'font-size-600': {value: '36px'},
  },
  shadow: {
    'shadow-inset-lg': {
      value:
        'inset -1px 0px 1px rgba(0, 0, 0, 0.2), inset 1px 0px 1px rgba(0, 0, 0, 0.2), inset 0px 2px 1px rgba(0, 0, 0, 0.6)',
    },
    'shadow-inset-md': {
      value:
        'inset -1px 0px 1px rgba(0, 0, 0, 0.12), inset 1px 0px 1px rgba(0, 0, 0, 0.12), inset 0px 2px 1px rgba(0, 0, 0, 0.2)',
    },
    'shadow-inset-sm': {
      value:
        'inset 0px 1px 1px rgba(0, 0, 0, 0.15), inset 0px 1px 2px rgba(255, 255, 255, 0.15)',
    },
    'shadow-xs': {value: '0px 1px 0px rgba(0, 0, 0, 0.07)'},
    'shadow-sm': {value: '0px 3px 1px -1px rgba(0, 0, 0, 0.07)'},
    'shadow-md': {value: '0px 4px 6px -2px rgba(0, 0, 0, 0.2)'},
    'shadow-lg': {value: '0px 8px 16px -4px rgba(0, 0, 0, 0.22)'},
    'shadow-xl': {value: '0px 12px 20px -8px rgba(0, 0, 0, 0.24)'},
    'shadow-2xl': {value: '0px 20px 20px -8px rgba(0, 0, 0, 0.28)'},
  },
  color: {
    'color-bg-inverse': {value: colors.gray[16]()},
    'color-bg-inset-strong': {value: colors.gray[15]()},
    'color-bg-inverse-hover': {value: colors.gray[14]()},
    'color-bg-inverse-active': {value: colors.gray[13]()},
    'color-bg-strong-hover': {value: colors.gray[9]()},
    'color-bg-strong-active': {value: colors.gray[10]()},
    'color-bg-strong': {value: colors.gray[8]()},
    'color-bg-subdued-active': {value: colors.gray[7]()},
    'color-bg-disabled': {value: colors.gray[7]()},
    'color-bg-interactive-disabled': {value: colors.gray[7]()},
    'color-bg-app': {value: colors.gray[6]()},
    'color-bg-app-hover': {value: colors.gray[2]()},
    'color-bg-app-selected': {value: colors.gray[3]()},
    'color-bg-active': {value: colors.gray[4]()},
    'color-bg-subdued-hover': {value: colors.gray[6]()},
    'color-bg-inset': {value: colors.gray[6]()},
    'color-bg-hover': {value: colors.gray[3]()},
    'color-bg-subdued': {value: colors.gray[4]()},
    'color-bg-input': {value: colors.gray[1]()},
    'color-bg': {value: colors.gray[1]()},
    'color-bg-primary-active': {value: colors.gray[16]()},
    'color-bg-primary-hover': {value: colors.gray[16]()},
    'color-bg-primary': {value: colors.gray[15]()},
    'color-bg-success-strong': {value: colors.green[12]},
    'color-bg-success': {value: colors.green[3]},
    'color-bg-primary-subdued-active': {value: colors.gray[6]()},
    'color-bg-success-subdued': {value: colors.green[3]},
    'color-bg-primary-subdued-hover': {value: colors.gray[7]()},
    'color-bg-success-subdued-hover': {value: colors.green[5]},
    'color-bg-primary-subdued': {value: colors.gray[8]()},
    'color-bg-primary-subdued-selected': {value: colors.gray[6]()},
    'color-bg-critical-strong-active': {value: colors.red[14]},
    'color-bg-critical-strong-hover': {value: colors.red[13]},
    'color-bg-critical-strong': {value: colors.red[12]},
    'color-bg-critical-subdued-active': {value: colors.red[6]},
    'color-bg-critical': {value: colors.red[6]},
    'color-bg-critical-subdued': {value: colors.red[4]},
    'color-bg-critical-subdued-hover': {value: colors.red[5]},
    'color-bg-caution-strong': {value: colors.yellow[6]},
    'color-bg-caution': {value: colors.yellow[4]},
    'color-bg-caution-subdued-active': {value: colors.yellow[4]},
    'color-bg-caution-subdued': {value: colors.yellow[2]},
    'color-bg-caution-subdued-hover': {value: colors.yellow[3]},
    'color-bg-info-strong': {value: colors.azure[9]},
    'color-bg-info-subdued-active': {value: colors.azure[6]},
    'color-bg-info': {value: colors.azure[4]},
    'color-bg-info-subdued': {value: colors.azure[3]},
    'color-bg-info-subdued-hover': {value: colors.azure[4]},
    'color-bg-interactive-active': {value: colors.gray[14]()},
    'color-bg-interactive-hover': {value: colors.gray[15]()},
    'color-bg-interactive': {value: colors.gray[16]()},
    'color-bg-interactive-subdued-active': {value: colors.gray[6]()},
    'color-bg-interactive-subdued-hover': {value: colors.gray[7]()},
    'color-bg-interactive-subdued': {value: colors.gray[8]()},
    'color-bg-interactive-selected': {value: colors.gray[6]()},
    'color-bg-warning': {value: colors.orange[7]},
    'color-bg-magic-strong': {value: colors.purple[12]},
    'color-bg-magic-hover': {value: colors.purple[7]},
    'color-bg-magic-active': {value: colors.purple[8]},
    'color-bg-magic': {value: colors.purple[6]},
    'color-bg-magic-subdued-hover': {value: colors.purple[4]},
    'color-bg-magic-subdued-active': {value: colors.purple[6]},
    'color-bg-magic-subdued': {value: colors.purple[3]},
    'color-border-input-hover': {value: colors.gray[13]()},
    'color-border-inverse': {value: colors.gray[13]()},
    'color-border-strong-hover': {value: colors.gray[11]()},
    'color-border-input': {value: colors.gray[12]()},
    'color-border-hover': {value: colors.gray[10]()},
    'color-border-strong': {value: colors.gray[10]()},
    'color-border': {value: colors.gray[8]()},
    'color-border-disabled': {value: colors.gray[7]()},
    'color-border-subdued': {value: colors.gray[7]()},
    'color-border-interactive-disabled': {value: colors.gray[7]()},
    'color-border-primary': {value: colors.gray[8]()},
    'color-border-success': {value: colors.green[5]},
    'color-border-success-subdued': {value: colors.green[5]},
    'color-border-critical-active': {value: colors.red[11]},
    'color-border-critical-hover': {value: colors.red[10]},
    'color-border-critical': {value: colors.red[9]},
    'color-border-critical-subdued': {value: colors.red[9]},
    'color-border-caution': {value: colors.yellow[5]},
    'color-border-caution-subdued': {value: colors.yellow[5]},
    'color-border-info': {value: colors.azure[9]},
    'color-border-info-subdued': {value: colors.azure[9]},
    'color-border-interactive-active': {value: colors.blue[15]},
    'color-border-interactive-hover': {value: colors.blue[14]},
    'color-border-interactive': {value: colors.blue[13]},
    'color-border-interactive-focus': {value: colors.blue[13]},
    'color-border-interactive-subdued': {value: colors.blue[13]},
    'color-border-magic-strong': {value: colors.purple[12]},
    'color-border-magic': {value: colors.purple[10]},
    'color-icon-hover': {value: colors.gray[15]()},
    'color-icon': {value: colors.gray[14]()},
    'color-icon-subdued': {value: colors.gray[12]()},
    'color-icon-disabled': {value: colors.gray[10]()},
    'color-icon-interactive-disabled': {value: colors.gray[10]()},
    'color-icon-inverse': {value: colors.gray[8]()},
    'color-icon-on-color': {value: colors.gray[1]()},
    'color-icon-primary': {value: colors.gray[16]()},
    'color-icon-success': {value: colors.green[12]},
    'color-icon-critical': {value: colors.red[11]},
    'color-icon-caution': {value: colors.yellow[11]},
    'color-icon-info': {value: colors.azure[11]},
    'color-icon-warning': {value: colors.orange[11]},
    'color-icon-interactive-active': {value: colors.blue[15]},
    'color-icon-interactive-hover': {value: colors.blue[14]},
    'color-icon-interactive': {value: colors.blue[13]},
    'color-icon-interactive-inverse': {value: colors.blue[8]},
    'color-icon-magic': {value: colors.purple[13]},
    'color-text': {value: colors.gray[15]()},
    'color-text-subdued': {value: colors.gray[13]()},
    'color-text-disabled': {value: colors.gray[11]()},
    'color-text-interactive-disabled': {value: colors.gray[10]()},
    'color-text-inverse-subdued': {value: colors.gray[10]()},
    'color-text-inverse': {value: colors.gray[8]()},
    'color-text-on-color': {value: colors.gray[1]()},
    'color-text-success-strong': {value: colors.green[15]},
    'color-text-success': {value: colors.green[15]},
    'color-text-primary': {value: colors.gray[14]()},
    'color-text-primary-hover': {value: colors.gray[14]()},
    'color-text-critical-strong': {value: colors.red[14]},
    'color-text-critical-active': {value: colors.red[16]},
    'color-text-critical': {value: colors.red[14]},
    'color-text-caution-strong': {value: colors.yellow[15]},
    'color-text-caution': {value: colors.yellow[15]},
    'color-text-info-strong': {value: colors.azure[16]},
    'color-text-info': {value: colors.azure[14]},
    'color-text-warning-strong': {value: colors.orange[16]},
    'color-text-interactive-active': {value: colors.blue[15]},
    'color-text-interactive-hover': {value: colors.blue[14]},
    'color-text-interactive': {value: colors.blue[13]},
    'color-text-interactive-inverse': {value: colors.blue[8]},
    'color-text-magic-strong': {value: colors.purple[15]},
    'color-text-magic': {value: colors.purple[14]},
  },
});

export const metaThemeLightUplift = createMetaThemeVariant(
  metaThemeLightUpliftPartial,
);
