name: '@shopify/polaris-tokens CI'

on:
  pull_request:
    paths:
      - 'polaris-tokens/**'
  push:
    branches: main
    paths:
      - 'polaris-tokens/**'

jobs:
  test:
    name: Test with node v${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['14.17.0', '16.13.0']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: ${{ matrix.node_version }}
          cache: yarn

      - run: yarn --frozen-lockfile
      - run: yarn type-check
      - run: yarn workspace @shopify/polaris-tokens run test
