name: Check for non committable changes

on:
  push:
    paths:
      - 'stylelint-polaris/**'

jobs:
  test:
    name: Test with node v${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['14.17.0', '16.13.0']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: ${{ matrix.node_version }}
          cache: yarn

      - run: yarn --frozen-lockfile
      - run: yarn workspace @shopify/stylelint-polaris test
