name: Check for non committable changes

on:
  push:
    paths:
      - 'polaris-react/playground/Playground.tsx'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for changes to Playground.tsx
        run: |
          echo "Please remove changes from Playground.tsx before committing"
          exit 1
