name: Check for non committable changes

on:
  pull_request:
    paths:
      - 'polaris-react/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: filter
        with:
          filters: |
            playground:
              - 'polaris-react/playground/Playground.tsx'

      - name: Check for changes to Playground.tsx
        if: steps.filter.outputs.playground == 'true'
        run: |
          echo "Please remove changes from Playground.tsx before committing"
          exit 1
