name: Prerelease

on:
  push:
    branches:
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Check if Prerelease is enabled
        id: is_pre_enabled
        uses: andstor/file-existence-action@v1
        with:
          files: '.changeset/pre.json'

      - name: Enter prerelease mode
        if: steps.is_pre_enabled.outputs.files_exists == 'false'
        run: yarn changeset pre enter next

      - name: Create release Pull Request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
