name: Release Polaris for VS Code

on:
  push:
    paths:
      - 'polaris-for-vscode/CHANGELOG.md'
      - 'polaris-tokens/CHANGELOG.md'
    branches:
      - main

jobs:
  release-vscode:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        name: Checkout

      - name: Free up space on GitHub image
        run: |
          # Based on the official advice:
          # https://github.com/actions/virtual-environments/issues/2840#issuecomment-790492173
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Setup pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0

      - name: Setup Node from .nvmrc
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build extension
        run: pnpm build --filter=polaris-for-vscode

      - name: Publish extension in the marketplace
        run: pnpm --filter=polaris-for-vscode vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
