name: Sketchy release

on:
  push:
    branches:
      - fix-version-packages

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            **/.eslintcache
            **/.turbo
            node_modules/.cache/turbo
            polaris-react/.loom/cache
            polaris.shopify.com/.next/cache
          key: ${{ runner.os }}-node${{ matrix.node_version }}-test-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-node${{ matrix.node_version }}-test-v1-
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build packages
        run: yarn build

      - name: Sketchy publish
        run: |
          # cd polaris-react && echo "publish polaris"
          # cd ../polaris-tokens && echo "publish polaris-tokens"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
