name: Sketchy release

on: push

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run build
        run: yarn build

      - name: Publish to NPM
        run: cd polaris-react && yarn publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
