name: Slash Command

on:
  issue_comment:
    types:
      - created

jobs:
  slashCommand:
    name: Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          permission: admin
          issue-type: pull-request
          commands: snapshot-release
