name: Unpublish

on: [pull_request]

jobs:
  unpublish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Node with v16.13.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
          registry-url: https://registry.npmjs.org/

      - name: Unpublish Polaris for VS Code
        run: npm unpublish polaris-for-vscode --force
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Unpublish Polaris for Figma
        run: npm unpublish polaris-for-figma --force
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
